export const SEED_TOPICS = [
  {
    id: "backend",
    label: "Backend Fundamentals",
    icon: "⚙",
    color: "#E8A838",
    questions: [
      {
        id: "be1",
        subtopic: "API Design",
        popularity: 9,
        question: "How do you design a RESTful API with proper versioning, idempotency, and error responses?",
        question_pt: "Como você projeta uma API RESTful com versionamento, idempotência e respostas de erro adequados?",
        answer: "Use plural nouns for resource endpoints, proper HTTP methods, and meaningful status codes like 201 Created or 422 Unprocessable Entity. URI-based versioning (/v1/) is the most common approach because it's explicit and easy to debug. For mutation endpoints, require an idempotency key header so retried requests don't duplicate side effects, and return consistent error shapes that never leak stack traces in production.",
        answer_pt: "Use substantivos no plural para endpoints de recursos, métodos HTTP corretos e status codes significativos como 201 Created ou 422 Unprocessable Entity. O versionamento via URI (/v1/) é a abordagem mais comum por ser explícita e fácil de depurar. Para endpoints de mutação, exija um header de idempotency key para que requisições repetidas não dupliquem efeitos colaterais, e retorne formatos de erro consistentes que nunca exponham stack traces em produção.",
      },
      {
        id: "be2",
        subtopic: "Authentication",
        popularity: 9,
        question: "How do you implement authentication and authorization using JWT and OAuth 2.0?",
        question_pt: "Como você implementa autenticação e autorização usando JWT e OAuth 2.0?",
        answer: "JWTs are short-lived (15-30 minutes) signed tokens sent via Authorization Bearer headers, with longer-lived refresh tokens stored in HTTP-only cookies to mitigate XSS. OAuth 2.0 delegates auth to a third-party provider using the Authorization Code with PKCE flow for web apps. On the server, middleware validates the JWT signature, checks expiration, and attaches the decoded user before the route handler runs.",
        answer_pt: "JWTs são tokens assinados de curta duração (15-30 minutos) enviados via headers de Authorization Bearer, com refresh tokens de maior duração armazenados em cookies HTTP-only para mitigar XSS. O OAuth 2.0 delega a autenticação a um provedor terceiro usando o fluxo Authorization Code com PKCE para aplicações web. No servidor, um middleware valida a assinatura do JWT, verifica a expiração e anexa o usuário decodificado antes do route handler ser executado.",
      },
      {
        id: "be3",
        subtopic: "Design Patterns",
        popularity: 8,
        question: "How do you implement the Circuit Breaker pattern in a microservices architecture?",
        question_pt: "Como você implementa o padrão Circuit Breaker em uma arquitetura de microsserviços?",
        answer: "A circuit breaker wraps calls to external services and tracks failures — after a threshold of consecutive failures, the circuit opens and rejects requests immediately without hitting the downstream service. After a cooldown it enters half-open state, allows a few test requests through, and closes again on success. In Node.js, opossum provides a ready-made implementation; combine it with exponential backoff plus jitter to avoid retry storms.",
        answer_pt: "Um circuit breaker encapsula chamadas a serviços externos e rastreia falhas — após um limite de falhas consecutivas, o circuito abre e rejeita requisições imediatamente sem atingir o serviço downstream. Após um período de cooldown, entra em estado half-open, permite algumas requisições de teste passarem e fecha novamente em caso de sucesso. No Node.js, o opossum oferece uma implementação pronta; combine-o com exponential backoff mais jitter para evitar retry storms.",
      },
      {
        id: "be4",
        subtopic: "Error Handling",
        popularity: 9,
        question: "How do you handle centralized error handling in a Node.js/Express application?",
        question_pt: "Como você implementa tratamento de erros centralizado em uma aplicação Node.js/Express?",
        answer: "Register a four-parameter middleware (err, req, res, next) after all routes, and use an asyncHandler wrapper so rejected promises automatically forward to it via next(err). Distinguish operational errors from programmer errors — log full stacks for the latter, return sanitized responses to the client. Use process.on('unhandledRejection') and process.on('uncaughtException') as safety nets with graceful shutdown logic.",
        answer_pt: "Registre um middleware de quatro parâmetros (err, req, res, next) após todas as rotas, e use um wrapper asyncHandler para que promises rejeitadas sejam automaticamente encaminhadas via next(err). Diferencie erros operacionais de erros de programação — para os últimos, registre as stacks completas e retorne respostas sanitizadas ao cliente. Use process.on('unhandledRejection') e process.on('uncaughtException') como redes de segurança com lógica de graceful shutdown.",
      },
      {
        id: "be5",
        subtopic: "Caching",
        popularity: 8,
        question: "What caching strategies do you use, and how do you handle cache invalidation?",
        question_pt: "Quais estratégias de cache você usa e como lida com a invalidação de cache?",
        answer: "Cache-Aside is the most common pattern: check Redis first, fall back to the DB, then populate the cache. Invalidation is handled via TTL expiration or event-driven invalidation when data changes. Set explicit Cache-Control and ETag headers for HTTP caching so clients can use conditional requests to revalidate stale responses.",
        answer_pt: "Cache-Aside é o padrão mais comum: verifique o Redis primeiro, recorra ao banco de dados e então popule o cache. A invalidação é feita via expiração por TTL ou invalidação orientada a eventos quando os dados mudam. Defina headers explícitos de Cache-Control e ETag para caching HTTP para que os clientes possam usar requisições condicionais para revalidar respostas desatualizadas.",
      },
      {
        id: "be6",
        subtopic: "Databases",
        popularity: 8,
        question: "How do you design database schemas and optimize queries for a production application?",
        question_pt: "Como você projeta schemas de banco de dados e otimiza queries para uma aplicação em produção?",
        answer: "Use normalized relational schemas when data integrity and joins matter, and denormalized document schemas when read performance and flexibility matter more. Indexing is the primary optimization tool — create composite indexes matching your most frequent query patterns and use EXPLAIN ANALYZE to find slow queries. For large datasets, cursor-based pagination outperforms offset-based, and connection pooling avoids the overhead of creating new connections per request.",
        answer_pt: "Use schemas relacionais normalizados quando integridade dos dados e joins importam, e schemas de documentos desnormalizados quando performance de leitura e flexibilidade são mais importantes. Indexação é a principal ferramenta de otimização — crie índices compostos que correspondam aos seus padrões de query mais frequentes e use EXPLAIN ANALYZE para encontrar queries lentas. Para grandes volumes de dados, paginação baseada em cursor supera a baseada em offset, e connection pooling evita o overhead de criar novas conexões por requisição.",
      },
      {
        id: "be7",
        subtopic: "Microservices",
        popularity: 7,
        question: "How do you implement graceful shutdown in a Node.js service?",
        question_pt: "Como você implementa graceful shutdown em um serviço Node.js?",
        answer: "Listen for SIGTERM, call server.close() to stop accepting new connections, and let in-flight requests complete within a timeout before closing DB pools and message queue consumers. If the timeout expires, force exit with process.exit(1) to prevent hanging. Health check endpoints like /readyz should reflect the shutdown state so load balancers stop routing traffic to the draining instance.",
        answer_pt: "Escute o SIGTERM, chame server.close() para parar de aceitar novas conexões e deixe as requisições em andamento concluírem dentro de um timeout antes de fechar os pools de banco de dados e consumidores de fila de mensagens. Se o timeout expirar, force a saída com process.exit(1) para evitar que o processo trave. Endpoints de health check como /readyz devem refletir o estado de shutdown para que os load balancers parem de rotear tráfego para a instância em drenagem.",
      },
      {
        id: "be8",
        subtopic: "Design Patterns",
        popularity: 7,
        question: "How do you implement Dependency Injection in a Node.js/TypeScript application?",
        question_pt: "Como você implementa Dependency Injection em uma aplicação Node.js/TypeScript?",
        answer: "Dependency Injection means a class receives its dependencies as constructor parameters rather than creating them internally, enabling loose coupling and easy unit testing with mocks. In TypeScript, frameworks like NestJS or InversifyJS use decorators and reflection metadata to resolve dependencies automatically. Even without a framework, manual constructor injection at the composition root is effective and keeps code testable.",
        answer_pt: "Dependency Injection significa que uma classe recebe suas dependências como parâmetros do construtor em vez de criá-las internamente, possibilitando baixo acoplamento e testes unitários fáceis com mocks. No TypeScript, frameworks como NestJS ou InversifyJS usam decorators e reflection metadata para resolver dependências automaticamente. Mesmo sem um framework, a injeção manual via construtor na raiz de composição é eficaz e mantém o código testável.",
      },
    ],
  },
  {
    id: "typescript",
    label: "TypeScript",
    icon: "◇",
    color: "#3178c6",
    questions: [
      {
        id: "ts1",
        subtopic: "Generics",
        popularity: 10,
        question: "How do Generics work in TypeScript, and how do you constrain them?",
        question_pt: "Como os Generics funcionam no TypeScript e como você os restringe?",
        answer: "Generics parameterize types so a function or class works with multiple types without losing type information. You constrain them with the extends keyword — for example, T extends { length: number } — which is fundamentally different from any because the compiler still tracks the actual type throughout the function body. A practical example is a generic merge function typed as merge<T extends object, U extends object>(a: T, b: U): T & U.",
        answer_pt: "Generics parametrizam tipos para que uma função ou classe funcione com múltiplos tipos sem perder informações de tipo. Você os restringe com a palavra-chave extends — por exemplo, T extends { length: number } — o que é fundamentalmente diferente de any porque o compilador ainda rastreia o tipo real ao longo do corpo da função. Um exemplo prático é uma função merge genérica tipada como merge<T extends object, U extends object>(a: T, b: U): T & U.",
      },
      {
        id: "ts2",
        subtopic: "Type System",
        popularity: 10,
        question: "Explain the difference between `type` and `interface`. When would you use one over the other?",
        question_pt: "Explique a diferença entre `type` e `interface`. Quando você usaria um em vez do outro?",
        answer: "Interfaces support declaration merging, making them ideal for library augmentation and contracts that consumers extend. Type aliases can represent unions, intersections, mapped types, and primitives — things interfaces cannot. Use interface for public API surfaces you expect to be extended, and type for unions and advanced type-level computations.",
        answer_pt: "Interfaces suportam declaration merging, tornando-as ideais para augmentação de bibliotecas e contratos que consumidores estendem. Type aliases podem representar unions, intersections, mapped types e primitivos — coisas que interfaces não conseguem. Use interface para superfícies de API pública que você espera que sejam estendidas, e type para unions e computações avançadas em nível de tipo.",
      },
      {
        id: "ts3",
        subtopic: "Conditional Types",
        popularity: 9,
        question: "What are Conditional Types, and how does the `infer` keyword work?",
        question_pt: "O que são Conditional Types e como a palavra-chave `infer` funciona?",
        answer: "Conditional types follow T extends U ? X : Y — if T is assignable to U, resolve to X, otherwise Y. The infer keyword captures a type from a pattern inside the condition, like type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never to extract a function's return type. When applied to a union, conditional types distribute over each member automatically.",
        answer_pt: "Conditional types seguem T extends U ? X : Y — se T é atribuível a U, resolve para X, caso contrário Y. A palavra-chave infer captura um tipo de um padrão dentro da condição, como type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never para extrair o tipo de retorno de uma função. Quando aplicados a uma union, conditional types se distribuem sobre cada membro automaticamente.",
      },
      {
        id: "ts4",
        subtopic: "Type Guards",
        popularity: 9,
        question: "What are Type Guards, and how do you write a custom type guard?",
        question_pt: "O que são Type Guards e como você escreve um type guard personalizado?",
        answer: "Type guards narrow a variable's type inside a conditional block. Built-ins include typeof, instanceof, and the in operator. A custom type guard is a function whose return type is a type predicate — function isString(value: unknown): value is string — so TypeScript narrows the variable in the truthy branch. They're essential when working with discriminated unions and untyped API responses.",
        answer_pt: "Type guards restringem o tipo de uma variável dentro de um bloco condicional. Os built-ins incluem typeof, instanceof e o operador in. Um type guard personalizado é uma função cujo tipo de retorno é um predicado de tipo — function isString(value: unknown): value is string — para que o TypeScript restrinja a variável no branch verdadeiro. Eles são essenciais ao trabalhar com discriminated unions e respostas de API sem tipagem.",
      },
      {
        id: "ts5",
        subtopic: "Utility Types",
        popularity: 9,
        question: "What are the key Utility Types in TypeScript and when do you use them?",
        question_pt: "Quais são os principais Utility Types do TypeScript e quando você os usa?",
        answer: "The most commonly used are Partial<T> for update/patch functions, Pick and Omit for shaping subsets of a type, and Record<K, V> for typed dictionaries. More advanced ones like ReturnType<T> and Parameters<T> extract function signatures, and Extract/Exclude filter union members. Interviewers expect you to know how these are implemented internally using mapped and conditional types.",
        answer_pt: "Os mais usados são Partial<T> para funções de update/patch, Pick e Omit para moldar subconjuntos de um tipo, e Record<K, V> para dicionários tipados. Os mais avançados como ReturnType<T> e Parameters<T> extraem assinaturas de funções, e Extract/Exclude filtram membros de unions. Em entrevistas, espera-se que você saiba como eles são implementados internamente usando mapped types e conditional types.",
      },
      {
        id: "ts6",
        subtopic: "Mapped Types",
        popularity: 8,
        question: "What are Mapped Types and how do you use them to transform existing types?",
        question_pt: "O que são Mapped Types e como você os usa para transformar tipos existentes?",
        answer: "Mapped types iterate over the keys of an existing type using { [K in keyof T]: ... } to produce a new type with transformed properties. You can add or remove modifiers like readonly and ? using + or - prefixes. Built-in utility types like Partial, Required, and Readonly are all implemented as mapped types, and the as clause (TS 4.1+) lets you remap keys to generate things like getter-style method signatures.",
        answer_pt: "Mapped types iteram sobre as chaves de um tipo existente usando { [K in keyof T]: ... } para produzir um novo tipo com propriedades transformadas. Você pode adicionar ou remover modificadores como readonly e ? usando prefixos + ou -. Utility types built-in como Partial, Required e Readonly são todos implementados como mapped types, e a cláusula as (TS 4.1+) permite remapear chaves para gerar coisas como assinaturas de métodos no estilo getter.",
      },
      {
        id: "ts7",
        subtopic: "Enums vs Unions",
        popularity: 8,
        question: "Enums vs. Union Types: which should you prefer and why?",
        question_pt: "Enums vs. Union Types: qual você prefere e por quê?",
        answer: "Enums emit runtime JavaScript objects, which adds bundle size, while string literal unions like type Status = 'active' | 'inactive' are fully erased at compile time with zero runtime overhead. The modern best practice is to prefer string literal unions — they're lighter, more predictable, and integrate better with discriminated unions and exhaustiveness checks.",
        answer_pt: "Enums emitem objetos JavaScript em tempo de execução, o que aumenta o bundle, enquanto unions de literais de string como type Status = 'active' | 'inactive' são completamente apagadas em tempo de compilação com zero overhead em runtime. A melhor prática moderna é preferir unions de literais de string — são mais leves, mais previsíveis e se integram melhor com discriminated unions e verificações de exhaustividade.",
      },
      {
        id: "ts8",
        subtopic: "Discriminated Unions",
        popularity: 8,
        question: "What are Discriminated Unions, and how do they enable exhaustiveness checking?",
        question_pt: "O que são Discriminated Unions e como elas possibilitam a verificação de exhaustividade?",
        answer: "A discriminated union is a union of types sharing a common literal property (the discriminant), like type Shape = { kind: 'circle'; radius: number } | { kind: 'square'; side: number }. TypeScript narrows the type automatically in each switch branch. Adding a never assignment in the default case gives you compile-time exhaustiveness checking — if you add a new variant and forget to handle it, the compiler errors.",
        answer_pt: "Uma discriminated union é uma union de tipos que compartilham uma propriedade literal em comum (o discriminante), como type Shape = { kind: 'circle'; radius: number } | { kind: 'square'; side: number }. O TypeScript restringe o tipo automaticamente em cada branch do switch. Adicionar uma atribuição never no caso default fornece verificação de exhaustividade em tempo de compilação — se você adicionar uma nova variante e esquecer de tratá-la, o compilador gera um erro.",
      },
      {
        id: "ts9",
        subtopic: "Strict Mode",
        popularity: 7,
        question: "What does TypeScript's `strict` mode enable, and why is it important?",
        question_pt: "O que o modo `strict` do TypeScript habilita e por que ele é importante?",
        answer: "The strict flag bundles several checks, the most impactful being strictNullChecks, which makes null and undefined distinct types and eliminates an entire class of runtime errors by forcing you to handle them explicitly. It also enables strictFunctionTypes for contravariant parameter checking and strictPropertyInitialization. Enabling strict from the start is strongly recommended — retrofitting it onto a large codebase surfaces hundreds of latent type errors.",
        answer_pt: "A flag strict agrupa várias verificações, sendo a mais impactante o strictNullChecks, que torna null e undefined tipos distintos e elimina toda uma classe de erros em runtime ao forçar o tratamento explícito deles. Também habilita strictFunctionTypes para verificação contravariante de parâmetros e strictPropertyInitialization. Habilitar strict desde o início é fortemente recomendado — aplicá-lo retroativamente a um codebase grande expõe centenas de erros de tipo latentes.",
      },
      {
        id: "ts10",
        subtopic: "Module System",
        popularity: 7,
        question: "How does TypeScript's module system work, and what is the difference between `import type` and regular `import`?",
        question_pt: "Como o sistema de módulos do TypeScript funciona e qual é a diferença entre `import type` e um `import` regular?",
        answer: "import type is a type-only import that is completely erased during compilation, producing no runtime JavaScript — important for avoiding circular dependency issues and reducing bundle size. Since TypeScript 5.0, verbatimModuleSyntax enforces that type-only imports are explicitly marked. Understanding the boundary between type-space and value-space imports is a key signal of senior-level TypeScript fluency.",
        answer_pt: "import type é uma importação exclusiva de tipo que é completamente apagada durante a compilação, não produzindo nenhum JavaScript em runtime — importante para evitar problemas de dependência circular e reduzir o bundle. Desde o TypeScript 5.0, verbatimModuleSyntax garante que importações somente de tipo sejam explicitamente marcadas. Entender a fronteira entre importações de tipo e de valor é um sinal-chave de fluência em TypeScript em nível sênior.",
      },
    ],
  },
  {
    id: "react",
    label: "React",
    icon: "◎",
    color: "#61dafb",
    questions: [
      {
        id: "re1",
        subtopic: "Virtual DOM",
        popularity: 10,
        question: "What is the Virtual DOM and how does React's reconciliation algorithm work?",
        question_pt: "O que é o Virtual DOM e como funciona o algoritmo de reconciliação do React?",
        answer: "The Virtual DOM is a lightweight in-memory representation of the real DOM. When state changes, React diffs the new Virtual DOM tree against the previous one using its Fiber-based reconciliation algorithm, using element type and key props to identify what changed. This runs in O(n) time and produces a minimal set of real DOM mutations instead of re-rendering everything.",
        answer_pt: "O Virtual DOM é uma representação leve em memória do DOM real. Quando o estado muda, o React compara a nova árvore do Virtual DOM com a anterior usando seu algoritmo de reconciliação baseado em Fiber, usando o tipo do elemento e a prop key para identificar o que mudou. Isso roda em tempo O(n) e produz um conjunto mínimo de mutações no DOM real em vez de re-renderizar tudo.",
      },
      {
        id: "re2",
        subtopic: "Hooks",
        popularity: 10,
        question: "Explain the rules and internal mechanics of React Hooks. Why can't you call hooks inside conditions or loops?",
        question_pt: "Explique as regras e a mecânica interna dos React Hooks. Por que você não pode chamar hooks dentro de condicionais ou loops?",
        answer: "React stores hook values as a linked list on each component's Fiber node. On every render, it walks this list in order, so the calling sequence must be identical between renders. If a hook is inside a condition or loop, the call order can change, causing React to map state to the wrong hook — which is why the Rules of Hooks require hooks to always be called at the top level.",
        answer_pt: "O React armazena os valores dos hooks como uma linked list no nó Fiber de cada componente. A cada renderização, ele percorre essa lista em ordem, portanto a sequência de chamadas deve ser idêntica entre renderizações. Se um hook estiver dentro de uma condicional ou loop, a ordem de chamada pode mudar, fazendo o React mapear o estado para o hook errado — por isso as Regras dos Hooks exigem que os hooks sempre sejam chamados no nível superior.",
      },
      {
        id: "re3",
        subtopic: "Performance",
        popularity: 9,
        question: "What is the difference between `useMemo` and `useCallback`, and when should you use each?",
        question_pt: "Qual é a diferença entre `useMemo` e `useCallback`, e quando você deve usar cada um?",
        answer: "useMemo memoizes a computed value, ideal for expensive calculations like filtering large arrays. useCallback memoizes a function reference, which matters when passing callbacks to child components wrapped in React.memo — since a new function reference on every render would break the memo check. Don't apply either prematurely; the memoization itself has a cost.",
        answer_pt: "useMemo memoiza um valor computado, ideal para cálculos custosos como filtrar arrays grandes. useCallback memoiza uma referência de função, o que importa ao passar callbacks para componentes filhos encapsulados em React.memo — já que uma nova referência de função a cada renderização quebraria a verificação do memo. Não aplique nenhum dos dois prematuramente; a própria memoização tem um custo.",
      },
      {
        id: "re4",
        subtopic: "Hooks",
        popularity: 9,
        question: "How does `useEffect` work, including its cleanup function and dependency array?",
        question_pt: "Como o `useEffect` funciona, incluindo sua função de cleanup e o array de dependências?",
        answer: "useEffect synchronizes a component with an external system and runs after the browser paints, so it doesn't block the UI. An empty dependency array means it runs only on mount; specific values cause it to re-run when those values change. The cleanup function runs before unmount and before the effect re-executes, preventing memory leaks from subscriptions or timers.",
        answer_pt: "useEffect sincroniza um componente com um sistema externo e é executado após o navegador renderizar, portanto não bloqueia a UI. Um array de dependências vazio significa que ele roda apenas na montagem; valores específicos fazem com que seja re-executado quando esses valores mudam. A função de cleanup roda antes da desmontagem e antes de o efeito ser re-executado, evitando memory leaks de subscriptions ou timers.",
      },
      {
        id: "re5",
        subtopic: "React 18+",
        popularity: 8,
        question: "What are React 18's concurrent features, and how do `useTransition` and `startTransition` work?",
        question_pt: "Quais são os recursos de renderização concorrente do React 18 e como `useTransition` e `startTransition` funcionam?",
        answer: "React 18's concurrent rendering makes the process interruptible — high-priority updates like typing can pause lower-priority ones like filtering a large list. useTransition returns an isPending flag and a startTransition function that marks state updates as non-urgent, keeping the UI responsive. React 18 also introduced automatic batching, which groups multiple state updates into a single re-render even inside promises and timeouts.",
        answer_pt: "A renderização concorrente do React 18 torna o processo interrompível — atualizações de alta prioridade como digitação podem pausar as de baixa prioridade como filtrar uma lista grande. useTransition retorna uma flag isPending e uma função startTransition que marca atualizações de estado como não urgentes, mantendo a UI responsiva. O React 18 também introduziu o batching automático, que agrupa múltiplas atualizações de estado em uma única re-renderização mesmo dentro de promises e timeouts.",
      },
      {
        id: "re6",
        subtopic: "React 18+",
        popularity: 8,
        question: "What is React Suspense and how does it relate to code splitting and data fetching?",
        question_pt: "O que é o React Suspense e como ele se relaciona com code splitting e busca de dados?",
        answer: "Suspense lets components declare they're waiting for async data, showing a fallback UI until ready. Combined with React.lazy(), it enables code splitting with automatic loading states when a chunk hasn't loaded yet. In React 18+, Suspense integrates with streaming SSR so the server can flush HTML progressively, and frameworks like Next.js and TanStack Query use Suspense-compatible data fetching.",
        answer_pt: "Suspense permite que componentes declarem que estão aguardando dados assíncronos, exibindo uma UI de fallback até estarem prontos. Combinado com React.lazy(), ele habilita code splitting com estados de carregamento automáticos quando um chunk ainda não foi carregado. No React 18+, o Suspense se integra com streaming SSR para que o servidor possa enviar HTML progressivamente, e frameworks como Next.js e TanStack Query usam busca de dados compatível com Suspense.",
      },
      {
        id: "re7",
        subtopic: "Performance",
        popularity: 8,
        question: "How do you optimize performance in a React application rendering large datasets?",
        question_pt: "Como você otimiza a performance em uma aplicação React que renderiza grandes volumes de dados?",
        answer: "For large lists, use windowing libraries like react-window or react-virtuoso to render only visible items, dramatically reducing DOM nodes. React.memo prevents unnecessary re-renders of pure components, and useMemo stabilizes expensive derived data. At the architecture level, colocating state close to where it's used and lazy loading routes with React.lazy are the most impactful structural improvements.",
        answer_pt: "Para listas grandes, use bibliotecas de windowing como react-window ou react-virtuoso para renderizar apenas os itens visíveis, reduzindo drasticamente os nós do DOM. React.memo evita re-renderizações desnecessárias de componentes puros, e useMemo estabiliza dados derivados custosos. No nível de arquitetura, colocar o estado próximo a onde ele é usado e fazer lazy loading de rotas com React.lazy são as melhorias estruturais mais impactantes.",
      },
      {
        id: "re8",
        subtopic: "Patterns",
        popularity: 7,
        question: "Explain HOCs, render props, and compound components. When would you use each?",
        question_pt: "Explique HOCs, render props e compound components. Quando você usaria cada um?",
        answer: "HOCs wrap a component to add behavior like auth or theming, but can lead to wrapper hell — custom hooks have largely replaced them for logic reuse. Compound components like Tabs and Tabs.Panel use React Context internally so related children share implicit state without prop drilling, making them the preferred pattern for flexible UI APIs. Render props are a middle ground but rarely the cleanest solution in modern React.",
        answer_pt: "HOCs encapsulam um componente para adicionar comportamentos como autenticação ou theming, mas podem levar ao wrapper hell — custom hooks os substituíram em grande parte para reutilização de lógica. Compound components como Tabs e Tabs.Panel usam React Context internamente para que filhos relacionados compartilhem estado implícito sem prop drilling, tornando-os o padrão preferido para APIs de UI flexíveis. Render props são uma solução intermediária, mas raramente a mais limpa no React moderno.",
      },
      {
        id: "re9",
        subtopic: "Hooks",
        popularity: 7,
        question: "What is `useRef` and how does it differ from state? What are its common use cases?",
        question_pt: "O que é `useRef` e como ele difere do estado? Quais são seus casos de uso mais comuns?",
        answer: "useRef returns a mutable object with a .current property that persists across renders without triggering a re-render when it changes, unlike useState. It's most commonly used to hold a DOM element reference for things like focusing an input, but also works as an instance variable for storing interval IDs or previous values. The key rule is to avoid reading or writing ref.current during rendering itself.",
        answer_pt: "useRef retorna um objeto mutável com uma propriedade .current que persiste entre renderizações sem disparar uma re-renderização quando muda, ao contrário do useState. É mais comumente usado para armazenar uma referência a um elemento DOM para coisas como focar um input, mas também funciona como uma variável de instância para armazenar IDs de intervalos ou valores anteriores. A regra principal é evitar ler ou escrever em ref.current durante a própria renderização.",
      },
      {
        id: "re10",
        subtopic: "Custom Hooks",
        popularity: 7,
        question: "How do you design and build custom hooks, and what principles should guide their architecture?",
        question_pt: "Como você projeta e constrói custom hooks, e quais princípios devem guiar sua arquitetura?",
        answer: "Custom hooks are functions prefixed with use that encapsulate reusable stateful logic by composing built-in hooks. A well-designed hook like useFetch or useDebounce follows single responsibility, returns only what the consumer needs, and handles cleanup properly to prevent memory leaks. Keeping the API surface small and using TypeScript generics for type safety are the main design principles.",
        answer_pt: "Custom hooks são funções prefixadas com use que encapsulam lógica stateful reutilizável compondo hooks built-in. Um hook bem projetado como useFetch ou useDebounce segue o princípio de responsabilidade única, retorna apenas o que o consumidor precisa e lida com o cleanup corretamente para evitar memory leaks. Manter a superfície da API pequena e usar generics do TypeScript para segurança de tipos são os principais princípios de design.",
      },
    ],
  },
  {
    id: "nodejs",
    label: "Node.js",
    icon: "▣",
    color: "#68a063",
    questions: [
      {
        id: "nd1",
        subtopic: "Event Loop",
        popularity: 10,
        question: "Explain the Node.js Event Loop and its phases.",
        question_pt: "Explique o Event Loop do Node.js e suas fases.",
        answer: "The event loop processes async operations across six phases: Timers, Pending Callbacks, Poll (retrieving new I/O events), Check (setImmediate), and Close Callbacks. Between each phase, Node.js drains the nextTick queue and the microtask queue (Promises), which always run before advancing to the next phase. Misusing this leads to I/O starvation or unexpected execution order.",
        answer_pt: "O event loop processa operações assíncronas em seis fases: Timers, Pending Callbacks, Poll (recuperar novos eventos de I/O), Check (setImmediate) e Close Callbacks. Entre cada fase, o Node.js esgota a fila do nextTick e a fila de microtasks (Promises), que sempre rodam antes de avançar para a próxima fase. O mau uso disso leva ao I/O starvation ou a ordens de execução inesperadas.",
      },
      {
        id: "nd2",
        subtopic: "Clustering",
        popularity: 9,
        question: "What is the difference between Clustering and Worker Threads, and when would you use each?",
        question_pt: "Qual é a diferença entre Clustering e Worker Threads, e quando você usaria cada um?",
        answer: "The cluster module spawns multiple child processes with isolated memory, ideal for scaling I/O-bound HTTP servers across CPU cores. Worker Threads run within the same process and can share memory via SharedArrayBuffer, making them suited for CPU-intensive tasks like image processing. A practical pattern is to combine both: one cluster process per CPU core, with worker threads inside each process for heavy computation.",
        answer_pt: "O módulo cluster cria múltiplos processos filhos com memória isolada, ideal para escalar servidores HTTP com carga de I/O entre núcleos de CPU. Worker Threads rodam dentro do mesmo processo e podem compartilhar memória via SharedArrayBuffer, tornando-os adequados para tarefas intensivas em CPU como processamento de imagens. Um padrão prático é combinar os dois: um processo de cluster por núcleo de CPU, com worker threads dentro de cada processo para computação pesada.",
      },
      {
        id: "nd3",
        subtopic: "Error Handling",
        popularity: 9,
        question: "How do you handle errors properly in a production Node.js application?",
        question_pt: "Como você trata erros corretamente em uma aplicação Node.js em produção?",
        answer: "Distinguish operational errors from programmer bugs — operational errors are recoverable, bugs should trigger a controlled shutdown. In async/await code use try/catch; on event emitters always attach error handlers since an unhandled error event crashes the process. Use process.on('unhandledRejection') as a safety net and implement structured logging with pino or winston for production observability.",
        answer_pt: "Diferencie erros operacionais de bugs de programação — erros operacionais são recuperáveis, bugs devem disparar um shutdown controlado. Em código async/await use try/catch; em event emitters sempre anexe handlers de erro, pois um evento de erro não tratado trava o processo. Use process.on('unhandledRejection') como rede de segurança e implemente logging estruturado com pino ou winston para observabilidade em produção.",
      },
      {
        id: "nd4",
        subtopic: "Streams",
        popularity: 8,
        question: "What is backpressure in Node.js Streams and how do you handle it?",
        question_pt: "O que é backpressure em Streams do Node.js e como você lida com isso?",
        answer: "Backpressure occurs when a readable stream produces data faster than the writable stream can consume it, causing memory to grow unbounded. writable.write() returns false when the internal buffer exceeds highWaterMark, signaling the producer to pause until the drain event fires. The easiest correct solution is stream.pipeline(), which manages backpressure automatically — failing to handle it is one of the most common causes of memory issues in streaming applications.",
        answer_pt: "Backpressure ocorre quando um readable stream produz dados mais rápido do que o writable stream consegue consumir, fazendo a memória crescer sem limite. writable.write() retorna false quando o buffer interno excede o highWaterMark, sinalizando ao produtor para pausar até que o evento drain seja disparado. A solução correta mais simples é stream.pipeline(), que gerencia o backpressure automaticamente — não lidar com isso é uma das causas mais comuns de problemas de memória em aplicações com streaming.",
      },
      {
        id: "nd5",
        subtopic: "Event Loop",
        popularity: 8,
        question: "What is the difference between `process.nextTick()` and `setImmediate()`?",
        question_pt: "Qual é a diferença entre `process.nextTick()` e `setImmediate()`?",
        answer: "process.nextTick() drains completely between every event loop phase, so it executes before any pending I/O — the risk is that recursive calls can starve I/O entirely. setImmediate() runs in the Check phase, after Poll and pending I/O callbacks. Prefer setImmediate() for deferring work and reserve process.nextTick() for cases where a callback must run before any I/O in the current iteration.",
        answer_pt: "process.nextTick() é completamente esvaziado entre cada fase do event loop, portanto executa antes de qualquer I/O pendente — o risco é que chamadas recursivas podem privar completamente o I/O. setImmediate() roda na fase Check, após Poll e os callbacks de I/O pendentes. Prefira setImmediate() para adiar trabalho e reserve process.nextTick() para casos em que um callback precisa rodar antes de qualquer I/O na iteração atual.",
      },
      {
        id: "nd6",
        subtopic: "Security",
        popularity: 8,
        question: "What are the key Node.js security vulnerabilities and how do you mitigate them (OWASP)?",
        question_pt: "Quais são as principais vulnerabilidades de segurança no Node.js e como você as mitiga (OWASP)?",
        answer: "The critical risks are injection attacks, broken authentication, and insecure dependencies. Mitigate with input validation using zod or joi, parameterized queries to prevent injection, the helmet middleware for secure HTTP headers, and regular npm audit runs. Implement rate limiting, avoid eval() and dynamic require(), and follow least-privilege principles for service accounts and environment secrets.",
        answer_pt: "Os riscos críticos são ataques de injeção, autenticação quebrada e dependências inseguras. Mitigue com validação de entrada usando zod ou joi, queries parametrizadas para prevenir injeção, o middleware helmet para headers HTTP seguros e execuções regulares de npm audit. Implemente rate limiting, evite eval() e require() dinâmico, e siga os princípios de menor privilégio para contas de serviço e secrets de ambiente.",
      },
      {
        id: "nd7",
        subtopic: "Middleware",
        popularity: 8,
        question: "How does the Express.js middleware pattern work, and what happens if you don't call `next()`?",
        question_pt: "Como o padrão de middleware do Express.js funciona e o que acontece se você não chamar `next()`?",
        answer: "Middleware forms a sequential pipeline where each function receives req, res, and next. If next() is never called and no response is sent, the request hangs and the client times out. Error-handling middleware uses the special four-argument signature (err, req, res, next) and is invoked via next(err). Middleware ordering is critical — auth and security middleware must run before route handlers, error handlers must come last.",
        answer_pt: "O middleware forma um pipeline sequencial onde cada função recebe req, res e next. Se next() nunca for chamado e nenhuma resposta for enviada, a requisição trava e o cliente tem timeout. O middleware de tratamento de erros usa a assinatura especial de quatro argumentos (err, req, res, next) e é invocado via next(err). A ordem dos middlewares é crítica — middlewares de autenticação e segurança devem rodar antes dos route handlers, e os handlers de erro devem vir por último.",
      },
      {
        id: "nd8",
        subtopic: "Memory",
        popularity: 7,
        question: "How do you detect and prevent memory leaks in Node.js?",
        question_pt: "Como você detecta e previne memory leaks no Node.js?",
        answer: "Memory leaks most commonly come from forgotten event listeners, uncleaned timers, and closures retaining large objects. Detect them by taking heap snapshots in Chrome DevTools via --inspect or using clinic.js to visualize memory growth over time. Prevent them by using WeakMap for temporary caches, always calling removeListener() when done, and using bounded LRU caches instead of unbounded objects.",
        answer_pt: "Memory leaks mais comumente vêm de event listeners esquecidos, timers não limpos e closures retendo objetos grandes. Detecte-os tirando heap snapshots no Chrome DevTools via --inspect ou usando clinic.js para visualizar o crescimento de memória ao longo do tempo. Previna-os usando WeakMap para caches temporários, sempre chamando removeListener() quando terminar e usando caches LRU com limite em vez de objetos ilimitados.",
      },
      {
        id: "nd9",
        subtopic: "Process Management",
        popularity: 7,
        question: "How do you implement graceful shutdown and process management in Node.js?",
        question_pt: "Como você implementa graceful shutdown e gerenciamento de processos no Node.js?",
        answer: "Listen for SIGTERM, call server.close() to stop accepting connections, let in-flight requests complete, then close database pools and resources in order. When using PM2, configure kill_timeout and use pm2 reload instead of pm2 restart for zero-downtime deployments. Signal readiness with process.send('ready') when using PM2's wait_ready option so traffic isn't routed before full initialization.",
        answer_pt: "Escute o SIGTERM, chame server.close() para parar de aceitar conexões, deixe as requisições em andamento concluírem e então feche os pools de banco de dados e recursos em ordem. Ao usar PM2, configure kill_timeout e use pm2 reload em vez de pm2 restart para deploys sem downtime. Sinalize a prontidão com process.send('ready') ao usar a opção wait_ready do PM2 para que o tráfego não seja roteado antes da inicialização completa.",
      },
      {
        id: "nd10",
        subtopic: "Internals",
        popularity: 6,
        question: "What is the role of `libuv` in Node.js and how does the thread pool work?",
        question_pt: "Qual é o papel do `libuv` no Node.js e como o thread pool funciona?",
        answer: "libuv is the C library that provides Node.js with async I/O by abstracting OS-specific APIs like epoll on Linux and IOCP on Windows. It manages a default thread pool of 4 threads (configurable via UV_THREADPOOL_SIZE) for operations that can't be done async at the OS level — like file system calls, dns.lookup(), and some crypto operations. If all threads are busy, thread-pool-dependent operations queue up, which is why cpu-bound crypto can block I/O.",
        answer_pt: "libuv é a biblioteca C que fornece ao Node.js I/O assíncrono abstraindo APIs específicas do SO como epoll no Linux e IOCP no Windows. Ela gerencia um thread pool padrão de 4 threads (configurável via UV_THREADPOOL_SIZE) para operações que não podem ser feitas de forma assíncrona no nível do SO — como chamadas ao sistema de arquivos, dns.lookup() e algumas operações de crypto. Se todas as threads estiverem ocupadas, operações dependentes do thread pool ficam em fila, por isso crypto com uso intensivo de CPU pode bloquear o I/O.",
      },
    ],
  },
  {
    id: "datastructures",
    label: "Data Structures",
    icon: "◈",
    color: "#f97316",
    questions: [
      {
        id: "ds1",
        subtopic: "Arrays & Hash Tables",
        popularity: 10,
        question: "Two Sum: Find pairs in an array that sum to a target value.",
        question_pt: "Two Sum: encontre pares em um array cuja soma resulte em um valor alvo.",
        answer: "Use a hash map to store complements as you iterate: for each element, check if the complement (target minus current) already exists in the map. If it does, you found the pair; if not, store the current element. This gives O(n) time and O(n) space, trading memory for a single-pass solution instead of a brute-force O(n²) nested loop.",
        answer_pt: "Use uma hash map para armazenar complementos enquanto itera: para cada elemento, verifique se o complemento (alvo menos o atual) já existe no mapa. Se existir, você encontrou o par; se não, armazene o elemento atual. Isso resulta em O(n) de tempo e O(n) de espaço, trocando memória por uma solução de passagem única em vez de um loop aninhado de força bruta O(n²).",
      },
      {
        id: "ds2",
        subtopic: "Linked Lists",
        popularity: 9,
        question: "How do you reverse a singly linked list? Walk through both iterative and recursive approaches.",
        question_pt: "Como você inverte uma linked list simplesmente encadeada? Explique as abordagens iterativa e recursiva.",
        answer: "The iterative approach uses three pointers — prev, current, and next — walking the list once and redirecting each node's pointer to its predecessor. This runs in O(n) time and O(1) space. The recursive approach reverses from the tail back, but uses O(n) call stack space, making the iterative version preferable in memory-constrained environments.",
        answer_pt: "A abordagem iterativa usa três ponteiros — prev, current e next — percorrendo a lista uma vez e redirecionando o ponteiro de cada nó para seu predecessor. Isso roda em O(n) de tempo e O(1) de espaço. A abordagem recursiva inverte a partir da cauda, mas usa O(n) de espaço na call stack, tornando a versão iterativa preferível em ambientes com memória limitada.",
      },
      {
        id: "ds3",
        subtopic: "Trees (BST)",
        popularity: 9,
        question: "How do you validate a Binary Search Tree (BST)?",
        question_pt: "Como você valida uma Árvore de Busca Binária (BST)?",
        answer: "Pass min and max bounds down recursively — each node must fall strictly within its allowed range, not just be greater or less than its immediate parent. This is the key insight: a common mistake is only comparing a node to its direct children instead of enforcing the constraint across the entire subtree. The algorithm runs in O(n) time visiting every node once.",
        answer_pt: "Passe limites mínimos e máximos recursivamente — cada nó deve estar estritamente dentro do seu intervalo permitido, não apenas ser maior ou menor que seu pai imediato. Este é o insight principal: um erro comum é comparar um nó apenas com seus filhos diretos em vez de impor a restrição em toda a subárvore. O algoritmo roda em O(n) visitando cada nó uma vez.",
      },
      {
        id: "ds4",
        subtopic: "Graphs (BFS/DFS)",
        popularity: 9,
        question: "Number of Islands: How do you count connected components in a 2D grid using BFS/DFS?",
        question_pt: "Number of Islands: como você conta componentes conectados em uma grade 2D usando BFS/DFS?",
        answer: "Iterate through every cell, and whenever you find an unvisited land cell ('1'), trigger a BFS or DFS to mark all connected land as visited, then increment the island count. The key is marking cells visited as you go to avoid counting them twice. This runs in O(m*n) time since every cell is visited at most once.",
        answer_pt: "Itere por cada célula e sempre que encontrar uma célula de terra não visitada ('1'), dispare um BFS ou DFS para marcar toda a terra conectada como visitada, depois incremente a contagem de ilhas. O ponto-chave é marcar as células como visitadas conforme avança para evitar contá-las duas vezes. Isso roda em O(m*n) de tempo, pois cada célula é visitada no máximo uma vez.",
      },
      {
        id: "ds5",
        subtopic: "Big O Complexity",
        popularity: 9,
        question: "Explain Big O Complexity and compare operations across data structures.",
        question_pt: "Explique a Complexidade Big O e compare operações entre estruturas de dados.",
        answer: "Big O describes the upper bound of time or space growth as input size increases. Arrays give O(1) random access but O(n) insert/delete; hash tables give O(1) average for search, insert, and delete; balanced BSTs give O(log n) for all operations. Knowing these trade-offs is what drives data structure selection — for example, choosing a hash table for a lookup cache versus a heap for a priority queue.",
        answer_pt: "Big O descreve o limite superior do crescimento de tempo ou espaço conforme o tamanho da entrada aumenta. Arrays oferecem acesso aleatório em O(1) mas inserção/remoção em O(n); hash tables oferecem O(1) médio para busca, inserção e remoção; BSTs balanceadas oferecem O(log n) para todas as operações. Conhecer essas trocas é o que guia a seleção de estruturas de dados — por exemplo, escolher uma hash table para um cache de lookup versus um heap para uma fila de prioridade.",
      },
      {
        id: "ds6",
        subtopic: "Stacks & Queues",
        popularity: 8,
        question: "Implement a Stack using Queues (or Queue using Stacks). What are the trade-offs?",
        question_pt: "Implemente uma Stack usando Queues (ou Queue usando Stacks). Quais são as trocas envolvidas?",
        answer: "Implementing a stack with two queues makes either push or pop O(n) — you transfer all elements between queues to maintain LIFO order. Similarly, a queue with two stacks amortizes the cost: enqueue to one stack, and when dequeuing, transfer everything to the second stack only when it's empty. These are classic problems testing your understanding of how LIFO and FIFO ordering can be emulated.",
        answer_pt: "Implementar uma stack com duas queues torna push ou pop O(n) — você transfere todos os elementos entre as queues para manter a ordem LIFO. Da mesma forma, uma queue com duas stacks amortiza o custo: enqueue em uma stack e, ao fazer dequeue, transfira tudo para a segunda stack apenas quando ela estiver vazia. Esses são problemas clássicos que testam sua compreensão de como a ordenação LIFO e FIFO pode ser emulada.",
      },
      {
        id: "ds7",
        subtopic: "Linked Lists",
        popularity: 8,
        question: "How do you detect a cycle in a Linked List? (Floyd's Algorithm)",
        question_pt: "Como você detecta um ciclo em uma Linked List? (Algoritmo de Floyd)",
        answer: "Floyd's Tortoise and Hare algorithm uses two pointers: slow advances one node per step, fast advances two. If a cycle exists, they will eventually meet inside it; if fast reaches null, there's no cycle. This runs in O(n) time and O(1) space — no hash set needed — making it the optimal approach for cycle detection.",
        answer_pt: "O algoritmo da Tartaruga e da Lebre de Floyd usa dois ponteiros: slow avança um nó por passo, fast avança dois. Se um ciclo existir, eles eventualmente se encontrarão dentro dele; se fast atingir null, não há ciclo. Isso roda em O(n) de tempo e O(1) de espaço — sem necessidade de hash set — tornando-o a abordagem ótima para detecção de ciclos.",
      },
      {
        id: "ds8",
        subtopic: "Heaps",
        popularity: 8,
        question: "How do you find the Kth largest element in an array using a Min-Heap?",
        question_pt: "Como você encontra o K-ésimo maior elemento em um array usando um Min-Heap?",
        answer: "Maintain a min-heap of exactly K elements. As you iterate through the array, if the current element is larger than the heap's minimum root, replace it and heapify. After processing all elements, the root is the Kth largest. This runs in O(n log k) time — far better than sorting the full array at O(n log n) when K is small.",
        answer_pt: "Mantenha um min-heap com exatamente K elementos. Enquanto itera pelo array, se o elemento atual for maior que a raiz mínima do heap, substitua-a e faça o heapify. Após processar todos os elementos, a raiz é o K-ésimo maior. Isso roda em O(n log k) de tempo — muito melhor do que ordenar o array completo em O(n log n) quando K é pequeno.",
      },
      {
        id: "ds9",
        subtopic: "Graphs (Topological Sort)",
        popularity: 8,
        question: "Course Schedule: How do you detect if all courses can be completed (topological sort)?",
        question_pt: "Course Schedule: como você detecta se todos os cursos podem ser concluídos (ordenação topológica)?",
        answer: "Model courses as a directed graph and use Kahn's algorithm: repeatedly remove nodes with zero in-degree, decrementing neighbors' counts. If all nodes are removed, a valid topological order exists; if nodes remain, there's a cycle and not all courses can be completed. This runs in O(V+E) time.",
        answer_pt: "Modele os cursos como um grafo dirigido e use o algoritmo de Kahn: remova repetidamente nós com in-degree zero, decrementando as contagens dos vizinhos. Se todos os nós forem removidos, existe uma ordenação topológica válida; se restarem nós, há um ciclo e nem todos os cursos podem ser concluídos. Isso roda em O(V+E) de tempo.",
      },
      {
        id: "ds10",
        subtopic: "Tries",
        popularity: 7,
        question: "How do you implement an Autocomplete System using a Trie?",
        question_pt: "Como você implementa um sistema de Autocomplete usando uma Trie?",
        answer: "A Trie stores words character by character, so finding all words with a given prefix means traversing to the prefix node, then doing a DFS to collect everything below it. Insertion and prefix search both run in O(m) time where m is the word length. At scale, you pre-compute the top-K suggestions at each node so autocomplete queries don't require a full DFS on every keystroke.",
        answer_pt: "Uma Trie armazena palavras caractere por caractere, então encontrar todas as palavras com um dado prefixo significa percorrer até o nó do prefixo e depois fazer um DFS para coletar tudo abaixo dele. Inserção e busca por prefixo rodam em O(m) de tempo, onde m é o comprimento da palavra. Em escala, você pré-computa as top-K sugestões em cada nó para que as queries de autocomplete não exijam um DFS completo a cada tecla pressionada.",
      },
    ],
  },
  {
    id: "systemdesign",
    label: "System Design",
    icon: "△",
    color: "#a855f7",
    questions: [
      {
        id: "sd1",
        subtopic: "URL Shortener",
        popularity: 10,
        question: "Design a URL Shortener (e.g., TinyURL, bit.ly)",
        question_pt: "Projete um encurtador de URL (ex: TinyURL, bit.ly)",
        answer: "Generate a unique short key using Base62 encoding or a hash with collision resolution, store the mapping in a key-value database, and redirect via HTTP 301 or 302. Use Redis to cache hot URLs for sub-50ms lookups since the read-to-write ratio is roughly 100:1. The main design decisions are choosing between pre-generated keys versus on-demand hashing, and whether 301 (permanent, browser-cached) or 302 (temporary, trackable) redirects better fit the use case.",
        answer_pt: "Gere uma chave curta única usando codificação Base62 ou um hash com resolução de colisão, armazene o mapeamento em um banco de dados chave-valor e redirecione via HTTP 301 ou 302. Use Redis para fazer cache das URLs mais acessadas para lookups abaixo de 50ms, já que a razão leitura/escrita é de aproximadamente 100:1. As principais decisões de design são escolher entre chaves pré-geradas versus hashing sob demanda, e se redirecionamentos 301 (permanente, com cache no navegador) ou 302 (temporário, rastreável) se encaixam melhor no caso de uso.",
      },
      {
        id: "sd2",
        subtopic: "Chat System",
        popularity: 9,
        question: "Design a Chat/Messaging System (e.g., WhatsApp, Messenger)",
        question_pt: "Projete um sistema de Chat/Mensagens (ex: WhatsApp, Messenger)",
        answer: "Maintain persistent WebSocket connections for real-time delivery. The chat service checks a presence service (backed by Redis) to determine if the recipient is online — if so, deliver via WebSocket; if offline, queue the message and send a push notification. Store message history in Cassandra or HBase for its high write throughput and time-series access patterns.",
        answer_pt: "Mantenha conexões WebSocket persistentes para entrega em tempo real. O serviço de chat verifica um serviço de presença (baseado em Redis) para determinar se o destinatário está online — se estiver, entregue via WebSocket; se estiver offline, enfileire a mensagem e envie uma notificação push. Armazene o histórico de mensagens no Cassandra ou HBase por seu alto throughput de escrita e padrões de acesso em séries temporais.",
      },
      {
        id: "sd3",
        subtopic: "Rate Limiter",
        popularity: 9,
        question: "Design a Rate Limiter",
        question_pt: "Projete um Rate Limiter",
        answer: "Cap API calls per client within a time window and return HTTP 429 when exceeded. The token bucket algorithm is the most practical: it allows controlled bursts while enforcing an average rate. Store counters in Redis for sub-millisecond atomic increments using INCR with TTL. Implement at the API gateway layer so every downstream service gets protection without duplicating logic.",
        answer_pt: "Limite as chamadas de API por cliente dentro de uma janela de tempo e retorne HTTP 429 quando excedido. O algoritmo de token bucket é o mais prático: permite bursts controlados enquanto impõe uma taxa média. Armazene contadores no Redis para incrementos atômicos abaixo de milissegundo usando INCR com TTL. Implemente na camada de API gateway para que cada serviço downstream receba proteção sem duplicar lógica.",
      },
      {
        id: "sd4",
        subtopic: "News Feed",
        popularity: 9,
        question: "Design a Social Media News Feed (e.g., Facebook, Twitter)",
        question_pt: "Projete um Feed de Notícias de Rede Social (ex: Facebook, Twitter)",
        answer: "Fan-out-on-write pre-computes each user's feed on post, enabling fast reads but expensive writes for users with millions of followers. The optimal approach is a hybrid: push to regular users' feed caches on write, but pull celebrity posts at read time to avoid fan-out storms. A ranking service then applies relevance scoring before serving the final feed.",
        answer_pt: "Fan-out-on-write pré-computa o feed de cada usuário na postagem, permitindo leituras rápidas mas escritas custosas para usuários com milhões de seguidores. A abordagem ótima é híbrida: enviar para os caches de feed de usuários comuns na escrita, mas buscar posts de celebridades no momento da leitura para evitar fan-out storms. Um serviço de ranking aplica então uma pontuação de relevância antes de servir o feed final.",
      },
      {
        id: "sd5",
        subtopic: "Notification System",
        popularity: 8,
        question: "Design a Notification System",
        question_pt: "Projete um Sistema de Notificações",
        answer: "Decouple triggering from delivery: the notification service validates and enriches the request, checks user preferences, then publishes to prioritized Kafka topics. Channel workers (APNs/FCM for push, SES for email, Twilio for SMS) consume independently and handle retries. Failed deliveries go to a dead letter queue for inspection and reprocessing.",
        answer_pt: "Desacople o disparo da entrega: o serviço de notificação valida e enriquece a requisição, verifica as preferências do usuário e publica em tópicos Kafka priorizados. Workers de canal (APNs/FCM para push, SES para email, Twilio para SMS) consomem independentemente e lidam com retentativas. Entregas com falha vão para uma dead letter queue para inspeção e reprocessamento.",
      },
      {
        id: "sd6",
        subtopic: "Database Sharding",
        popularity: 7,
        question: "Design Database Sharding",
        question_pt: "Projete um sistema de Sharding de Banco de Dados",
        answer: "Shard key selection is the most critical decision — a good key distributes load evenly and keeps related queries on one shard to avoid cross-shard joins. Consistent hashing with virtual nodes is the standard approach because adding or removing a shard only moves approximately 1/N of the data instead of reshuffling everything. Directory-based sharding adds flexibility at the cost of a lookup service becoming a bottleneck.",
        answer_pt: "A seleção da shard key é a decisão mais crítica — uma boa chave distribui a carga uniformemente e mantém queries relacionadas em um único shard para evitar joins entre shards. Consistent hashing com nós virtuais é a abordagem padrão porque adicionar ou remover um shard move apenas aproximadamente 1/N dos dados em vez de reorganizar tudo. O sharding baseado em diretório adiciona flexibilidade ao custo de um serviço de lookup se tornar um gargalo.",
      },
      {
        id: "sd7",
        subtopic: "File Storage",
        popularity: 7,
        question: "Design a File Storage System (e.g., Google Drive, Dropbox)",
        question_pt: "Projete um Sistema de Armazenamento de Arquivos (ex: Google Drive, Dropbox)",
        answer: "Split files into chunks (typically ~4MB), identify each by content hash for deduplication and delta sync, and store chunks in object storage like S3. File metadata — hierarchy, permissions, versions — lives in a relational database. A sync service uses WebSockets or long polling to notify connected devices of changes in real time.",
        answer_pt: "Divida os arquivos em chunks (tipicamente ~4MB), identifique cada um por hash de conteúdo para deduplicação e delta sync, e armazene os chunks em object storage como S3. Os metadados dos arquivos — hierarquia, permissões, versões — ficam em um banco de dados relacional. Um serviço de sincronização usa WebSockets ou long polling para notificar os dispositivos conectados sobre mudanças em tempo real.",
      },
      {
        id: "sd8",
        subtopic: "Search Autocomplete",
        popularity: 7,
        question: "Design a Search Autocomplete / Typeahead System",
        question_pt: "Projete um sistema de Autocomplete / Typeahead de Busca",
        answer: "The core data structure is a Trie with pre-computed top-K suggestions at each node, held in memory for microsecond lookups. At scale, partition the trie via range-based sharding across servers, and decouple reads from updates — queries hit the in-memory trie while search log aggregation pipelines rebuild and atomically swap in updated tries. Cache popular prefixes aggressively at the CDN edge.",
        answer_pt: "A estrutura de dados central é uma Trie com as top-K sugestões pré-computadas em cada nó, mantida em memória para lookups em microssegundos. Em escala, particione a trie via sharding baseado em intervalo entre servidores, e desacople leituras de atualizações — as queries acessam a trie em memória enquanto pipelines de agregação de logs de busca reconstruem e trocam atomicamente as tries atualizadas. Faça cache agressivo de prefixos populares na borda da CDN.",
      },
      {
        id: "sd9",
        subtopic: "CDN",
        popularity: 6,
        question: "Design a CDN (Content Delivery Network)",
        question_pt: "Projete uma CDN (Content Delivery Network)",
        answer: "Geographically distributed edge servers cache content close to users, with DNS geo-routing directing each request to the nearest edge PoP. On a cache hit, the edge serves directly in under 10ms. On a miss, it fetches from a shield cache or the origin, caches the response with a TTL, and serves it. Invalidation is handled via TTL expiry, versioned URLs, or a purge API for urgent updates.",
        answer_pt: "Servidores de borda distribuídos geograficamente fazem cache de conteúdo próximo aos usuários, com DNS geo-routing direcionando cada requisição ao PoP de borda mais próximo. Em um cache hit, a borda serve diretamente em menos de 10ms. Em um cache miss, ela busca de um shield cache ou da origem, faz cache da resposta com um TTL e a serve. A invalidação é feita via expiração de TTL, URLs versionadas ou uma API de purga para atualizações urgentes.",
      },
      {
        id: "sd10",
        subtopic: "Load Balancer",
        popularity: 6,
        question: "Design a Load Balancer",
        question_pt: "Projete um Load Balancer",
        answer: "Load balancers operate at Layer 4 (TCP — fast, IP/port based) or Layer 7 (HTTP — smart, can route by URL path or headers). Least connections and consistent hashing are the most useful algorithms: least connections routes to the least busy server, while consistent hashing enables sticky sessions without centralized state. Health checks continuously probe backends and remove unhealthy instances from the pool automatically.",
        answer_pt: "Load balancers operam na Camada 4 (TCP — rápido, baseado em IP/porta) ou na Camada 7 (HTTP — inteligente, pode rotear por caminho de URL ou headers). Least connections e consistent hashing são os algoritmos mais úteis: least connections roteia para o servidor menos ocupado, enquanto consistent hashing habilita sticky sessions sem estado centralizado. Health checks sondam continuamente os backends e removem instâncias não saudáveis do pool automaticamente.",
      },
    ],
  },
  {
    id: "mycareer",
    label: "My Career",
    icon: "★",
    color: "#E8A838",
    questions: [
      {
        id: "cv1",
        subtopic: "RAG & AI Systems",
        popularity: 10,
        question: "You mention building RAG systems with pgVector and Qdrant. Walk me through the full pipeline — from document ingestion to semantic retrieval. What chunking strategy did you use and why?",
        question_pt: "Você menciona ter construído sistemas RAG com pgVector e Qdrant. Me explique o pipeline completo — desde a ingestão de documentos até a recuperação semântica. Qual estratégia de chunking você usou e por quê?",
        answer: "At Lex Consultoria, I built a RAG pipeline on top of TOTVS ERP data: documents are chunked using a sliding window with 50-token overlap to preserve context across boundaries, embedded with OpenAI's text-embedding-ada-002, and stored in pgVector — I chose pgVector because the HR data already lived in PostgreSQL, avoiding an extra infrastructure dependency. At query time, the user's question is embedded and a cosine similarity search retrieves the top-k chunks, which are injected into the GPT-4 prompt as grounded context. At TateAI I used Qdrant instead because we needed faster similarity search at scale with metadata filtering.",
        answer_pt: "Na Lex Consultoria, construí um pipeline RAG sobre dados do ERP TOTVS: os documentos são divididos em chunks com uma janela deslizante e sobreposição de 50 tokens para preservar o contexto entre fronteiras, embutidos com o text-embedding-ada-002 da OpenAI e armazenados no pgVector — escolhi pgVector porque os dados de RH já estavam no PostgreSQL, evitando uma dependência extra de infraestrutura. No momento da query, a pergunta do usuário é embutida e uma busca por similaridade de cosseno recupera os top-k chunks, que são injetados no prompt do GPT-4 como contexto fundamentado. Na TateAI usei Qdrant porque precisávamos de busca por similaridade mais rápida em escala com filtragem por metadados.",
      },
      {
        id: "cv2",
        subtopic: "System Architecture",
        popularity: 10,
        question: "At BTG Pactual you processed $10M+ daily transactions. How did you architect the system for reliability at that scale? What happens when a downstream service fails?",
        question_pt: "No BTG Pactual você processou mais de $10M em transações diárias. Como você arquitetou o sistema para confiabilidade nessa escala? O que acontece quando um serviço downstream falha?",
        answer: "The system was built on AWS Lambda, DynamoDB, and Kafka — each transaction publishes to a Kafka topic and downstream consumers process independently, so a failure in one consumer doesn't block others. For financial reliability, we used idempotency keys to prevent duplicate transactions on retries and DLQs for failed events. Circuit breakers prevented cascading failures and we achieved 99.9% uptime at 200ms average latency.",
        answer_pt: "O sistema foi construído sobre AWS Lambda, DynamoDB e Kafka — cada transação publica em um tópico Kafka e os consumidores downstream processam de forma independente, portanto uma falha em um consumidor não bloqueia os outros. Para confiabilidade financeira, usamos idempotency keys para evitar transações duplicadas em retentativas e DLQs para eventos com falha. Circuit breakers evitaram falhas em cascata e alcançamos 99,9% de uptime com 200ms de latência média.",
      },
      {
        id: "cv3",
        subtopic: "Real-time Systems",
        popularity: 9,
        question: "You handled 1000+ concurrent WebSocket connections for chat streaming at TateAI. How did you manage connection lifecycle, backpressure, and scaling?",
        question_pt: "Você gerenciou mais de 1000 conexões WebSocket simultâneas para streaming de chat na TateAI. Como você gerenciou o ciclo de vida das conexões, o backpressure e o escalonamento?",
        answer: "A connection registry tracked user sessions, handled heartbeats, and cleaned up on disconnect. For LLM streaming backpressure, I forwarded tokens to the client as they arrived from the LLM API, and paused the upstream read when the client's buffer was full. Scaling used multiple Node.js instances behind a load balancer with sticky sessions and Redis pub/sub to broadcast messages across instances.",
        answer_pt: "Um connection registry rastreava as sessões dos usuários, gerenciava heartbeats e fazia a limpeza na desconexão. Para o backpressure do streaming de LLM, encaminhava os tokens ao cliente conforme chegavam da API do LLM e pausava a leitura upstream quando o buffer do cliente estava cheio. O escalonamento usava múltiplas instâncias Node.js por trás de um load balancer com sticky sessions e Redis pub/sub para transmitir mensagens entre as instâncias.",
      },
      {
        id: "cv4",
        subtopic: "Migration & Optimization",
        popularity: 9,
        question: "You led migrating Java services to Node.js at BTG Pactual, reducing costs by 35%. How did you approach this migration without downtime?",
        question_pt: "Você liderou a migração de serviços Java para Node.js no BTG Pactual, reduzindo custos em 35%. Como você conduziu essa migração sem downtime?",
        answer: "I used the strangler fig pattern — building the Node.js replacement alongside the Java service, then using API Gateway weighted routing to shift traffic gradually: 10%, 25%, 50%, 100% while monitoring error rates and latency. Cost savings came from Lambda's pay-per-invocation model versus always-on ECS containers, and response times improved 45% because Node.js handles I/O-bound workloads more efficiently.",
        answer_pt: "Usei o padrão strangler fig — construindo o substituto em Node.js paralelamente ao serviço Java e usando o roteamento ponderado do API Gateway para transferir tráfego gradualmente: 10%, 25%, 50%, 100% monitorando as taxas de erro e latência. A economia de custos veio do modelo pay-per-invocation do Lambda versus containers ECS sempre ativos, e os tempos de resposta melhoraram 45% porque o Node.js lida com cargas de trabalho de I/O de forma mais eficiente.",
      },
      {
        id: "cv5",
        subtopic: "Telemedicine Platform",
        popularity: 9,
        question: "Tell me about the telemedicine platform at Lex Consultoria. How did you handle video call reliability, medical data security, and serving 20,000+ employees?",
        question_pt: "Me fale sobre a plataforma de telemedicina na Lex Consultoria. Como você lidou com a confiabilidade das videochamadas, a segurança dos dados médicos e o atendimento de mais de 20.000 funcionários?",
        answer: "We self-hosted Jitsi for data sovereignty and implemented automatic quality adaptation with fallback to audio-only and reconnection with session persistence for reliability. Medical data follows LGPD: AES-256 encryption at rest, TLS 1.3 in transit, S3 bucket policies with access logging for audit. The React frontend uses WebSockets for real-time presence, with role-based access control covering all 20,000+ employees.",
        answer_pt: "Hospedamos o Jitsi internamente para soberania dos dados e implementamos adaptação automática de qualidade com fallback para apenas áudio e reconexão com persistência de sessão para confiabilidade. Os dados médicos seguem a LGPD: criptografia AES-256 em repouso, TLS 1.3 em trânsito, políticas de bucket S3 com logging de acesso para auditoria. O frontend em React usa WebSockets para presença em tempo real, com controle de acesso baseado em papéis cobrindo todos os mais de 20.000 funcionários.",
      },
      {
        id: "cv6",
        subtopic: "AI-Assisted Development",
        popularity: 8,
        question: "You claim shipping features 3x faster using AI-assisted development tools. Can you give a concrete example? How do you ensure code quality?",
        question_pt: "Você afirma entregar features 3x mais rápido usando ferramentas de desenvolvimento assistido por IA. Você pode dar um exemplo concreto? Como você garante a qualidade do código?",
        answer: "Building a financial report module at BTG that would normally take two weeks took three days using Claude Code for architecture scaffolding, Copilot for boilerplate, and Amazon Q for AWS configurations. Quality assurance is critical — I never accept AI output blindly: I review every line for security issues, verify business logic matches requirements, and run the full test suite before any PR is opened.",
        answer_pt: "Construir um módulo de relatórios financeiros no BTG que normalmente levaria duas semanas levou três dias usando Claude Code para scaffolding da arquitetura, Copilot para boilerplate e Amazon Q para configurações AWS. A garantia de qualidade é crítica — nunca aceito o output da IA cegamente: reviso cada linha em busca de problemas de segurança, verifico se a lógica de negócio corresponde aos requisitos e executo a suíte de testes completa antes de qualquer PR ser aberto.",
      },
      {
        id: "cv7",
        subtopic: "E-commerce & Performance",
        popularity: 8,
        question: "At FAVO you achieved 60% latency reduction. What specific optimizations did you make?",
        question_pt: "Na FAVO você alcançou 60% de redução de latência. Quais otimizações específicas você fez?",
        answer: "Distributed tracing revealed two main issues: N+1 query problems in order creation, fixed with DataLoader-style batching and denormalization into DynamoDB; and Lambda cold starts on critical paths, fixed with provisioned concurrency and reduced package sizes. Non-critical external service calls moved from synchronous to SQS-backed async. Combined, these dropped P95 latency from ~2.5s to ~1s and improved conversion rate by 35%.",
        answer_pt: "O rastreamento distribuído revelou dois problemas principais: problemas de query N+1 na criação de pedidos, resolvidos com batching no estilo DataLoader e desnormalização no DynamoDB; e cold starts do Lambda em caminhos críticos, resolvidos com provisioned concurrency e tamanhos de pacote reduzidos. Chamadas a serviços externos não críticos migraram de síncronas para assíncronas com suporte de SQS. Em conjunto, essas mudanças reduziram a latência P95 de ~2,5s para ~1s e melhoraram a taxa de conversão em 35%.",
      },
      {
        id: "cv8",
        subtopic: "Leadership",
        popularity: 8,
        question: "As a Tech Lead at Lex, how do you balance hands-on coding with leadership responsibilities?",
        question_pt: "Como Tech Lead na Lex, como você equilibra o trabalho de código com as responsabilidades de liderança?",
        answer: "I allocate roughly 60% coding and 40% leadership — code reviews, mentoring, planning, and stakeholder communication. For architectural decisions I write lightweight ADRs, present options with trade-offs, and take ownership of the outcome. Staying close to the code keeps me honest about estimates and means I can jump in directly during critical production situations.",
        answer_pt: "Distribuo aproximadamente 60% codificando e 40% em liderança — code reviews, mentoria, planejamento e comunicação com stakeholders. Para decisões de arquitetura escrevo ADRs leves, apresento opções com suas trocas e assumo a responsabilidade pelo resultado. Manter-me próximo ao código me deixa honesto nas estimativas e significa que posso entrar diretamente em situações críticas de produção.",
      },
      {
        id: "cv9",
        subtopic: "Anomaly Detection",
        popularity: 7,
        question: "How does your anomaly detection system with Gemini work for time-tracking at Lex?",
        question_pt: "Como funciona o seu sistema de detecção de anomalias com Gemini para controle de ponto na Lex?",
        answer: "The system feeds structured time-tracking data from TOTVS ERP to Gemini with a carefully engineered prompt defining anomaly categories and requesting confidence scores. To control false positives, I only flag items above 80% confidence and cross-reference against known exceptions like approved overtime and shift workers before surfacing anything to managers. This saves 20+ hours per week of manual review that previously required an HR analyst.",
        answer_pt: "O sistema alimenta o Gemini com dados estruturados de controle de ponto do ERP TOTVS usando um prompt cuidadosamente elaborado que define categorias de anomalias e solicita pontuações de confiança. Para controlar falsos positivos, sinalizamos apenas itens acima de 80% de confiança e cruzamos com exceções conhecidas como horas extras aprovadas e trabalhadores em turno antes de apresentar qualquer coisa aos gestores. Isso economiza mais de 20 horas por semana de revisão manual que antes exigia um analista de RH.",
      },
      {
        id: "cv10",
        subtopic: "Serverless Architecture",
        popularity: 8,
        question: "You've used AWS Lambda extensively. What are the real-world limitations you've hit, and how did you work around them?",
        question_pt: "Você usou AWS Lambda extensivamente. Quais são as limitações reais com que se deparou e como as contornou?",
        answer: "Cold starts on financial APIs were solved with provisioned concurrency; the 15-minute execution limit on document processing was solved by orchestrating multi-step workflows with Step Functions. For PostgreSQL connection management I used RDS Proxy to avoid exhausting connection limits at scale. I kept business logic in framework-agnostic modules with thin Lambda handlers to limit vendor lock-in — this architecture handled 100,000+ daily requests at 99.95% availability at FAVO.",
        answer_pt: "Cold starts nas APIs financeiras foram resolvidos com provisioned concurrency; o limite de execução de 15 minutos no processamento de documentos foi resolvido orquestrando fluxos de trabalho em múltiplas etapas com Step Functions. Para o gerenciamento de conexões com PostgreSQL usei RDS Proxy para evitar esgotar os limites de conexão em escala. Mantive a lógica de negócio em módulos agnósticos de framework com Lambda handlers finos para limitar o vendor lock-in — essa arquitetura processou mais de 100.000 requisições diárias com 99,95% de disponibilidade na FAVO.",
      },
    ],
  },
];

export const uid = () => Math.random().toString(36).slice(2, 9);

export function buildPrompt(topic, subtopic, count) {
  return `You are a senior software engineer preparing interview questions for developers specialising in TypeScript, React, and Node.js.

Generate exactly ${count} high-quality technical interview questions with detailed answers for the following:
- Topic: ${topic}
- Subtopic: ${subtopic}

Requirements:
- Questions should range from mid to senior level.
- Answers must be detailed (3–5 sentences minimum), accurate, and mention real-world usage.
- Include code snippets or examples where relevant (use plain text, no markdown fences).
- Cover different angles: conceptual understanding, practical usage, trade-offs.

Respond ONLY with a valid JSON array. No preamble, no markdown, no backticks.
Format:
[
  {
    "question": "...",
    "answer": "..."
  }
]`;
}
