export const SEED_TOPICS = [
  {
    id: "backend",
    label: "Backend Fundamentals",
    icon: "⚙",
    color: "#E8A838",
    questions: [
      { id: "be1", subtopic: "API Design", popularity: 9, question: "How do you design a RESTful API with proper versioning, idempotency, and error responses?", answer: "Use plural nouns for resource endpoints, proper HTTP methods, and meaningful status codes like 201 Created or 422 Unprocessable Entity. URI-based versioning (/v1/) is the most common approach because it's explicit and easy to debug. For mutation endpoints, require an idempotency key header so retried requests don't duplicate side effects, and return consistent error shapes that never leak stack traces in production." },
      { id: "be2", subtopic: "Authentication", popularity: 9, question: "How do you implement authentication and authorization using JWT and OAuth 2.0?", answer: "JWTs are short-lived (15-30 minutes) signed tokens sent via Authorization Bearer headers, with longer-lived refresh tokens stored in HTTP-only cookies to mitigate XSS. OAuth 2.0 delegates auth to a third-party provider using the Authorization Code with PKCE flow for web apps. On the server, middleware validates the JWT signature, checks expiration, and attaches the decoded user before the route handler runs." },
      { id: "be3", subtopic: "Design Patterns", popularity: 8, question: "How do you implement the Circuit Breaker pattern in a microservices architecture?", answer: "A circuit breaker wraps calls to external services and tracks failures — after a threshold of consecutive failures, the circuit opens and rejects requests immediately without hitting the downstream service. After a cooldown it enters half-open state, allows a few test requests through, and closes again on success. In Node.js, opossum provides a ready-made implementation; combine it with exponential backoff plus jitter to avoid retry storms." },
      { id: "be4", subtopic: "Error Handling", popularity: 9, question: "How do you handle centralized error handling in a Node.js/Express application?", answer: "Register a four-parameter middleware (err, req, res, next) after all routes, and use an asyncHandler wrapper so rejected promises automatically forward to it via next(err). Distinguish operational errors from programmer errors — log full stacks for the latter, return sanitized responses to the client. Use process.on('unhandledRejection') and process.on('uncaughtException') as safety nets with graceful shutdown logic." },
      { id: "be5", subtopic: "Caching", popularity: 8, question: "What caching strategies do you use, and how do you handle cache invalidation?", answer: "Cache-Aside is the most common pattern: check Redis first, fall back to the DB, then populate the cache. Invalidation is handled via TTL expiration or event-driven invalidation when data changes. Set explicit Cache-Control and ETag headers for HTTP caching so clients can use conditional requests to revalidate stale responses." },
      { id: "be6", subtopic: "Databases", popularity: 8, question: "How do you design database schemas and optimize queries for a production application?", answer: "Use normalized relational schemas when data integrity and joins matter, and denormalized document schemas when read performance and flexibility matter more. Indexing is the primary optimization tool — create composite indexes matching your most frequent query patterns and use EXPLAIN ANALYZE to find slow queries. For large datasets, cursor-based pagination outperforms offset-based, and connection pooling avoids the overhead of creating new connections per request." },
      { id: "be7", subtopic: "Microservices", popularity: 7, question: "How do you implement graceful shutdown in a Node.js service?", answer: "Listen for SIGTERM, call server.close() to stop accepting new connections, and let in-flight requests complete within a timeout before closing DB pools and message queue consumers. If the timeout expires, force exit with process.exit(1) to prevent hanging. Health check endpoints like /readyz should reflect the shutdown state so load balancers stop routing traffic to the draining instance." },
      { id: "be8", subtopic: "Design Patterns", popularity: 7, question: "How do you implement Dependency Injection in a Node.js/TypeScript application?", answer: "Dependency Injection means a class receives its dependencies as constructor parameters rather than creating them internally, enabling loose coupling and easy unit testing with mocks. In TypeScript, frameworks like NestJS or InversifyJS use decorators and reflection metadata to resolve dependencies automatically. Even without a framework, manual constructor injection at the composition root is effective and keeps code testable." },
    ],
  },
  {
    id: "typescript",
    label: "TypeScript",
    icon: "◇",
    color: "#3178c6",
    questions: [
      { id: "ts1", subtopic: "Generics", popularity: 10, question: "How do Generics work in TypeScript, and how do you constrain them?", answer: "Generics parameterize types so a function or class works with multiple types without losing type information. You constrain them with the extends keyword — for example, T extends { length: number } — which is fundamentally different from any because the compiler still tracks the actual type throughout the function body. A practical example is a generic merge function typed as merge<T extends object, U extends object>(a: T, b: U): T & U." },
      { id: "ts2", subtopic: "Type System", popularity: 10, question: "Explain the difference between `type` and `interface`. When would you use one over the other?", answer: "Interfaces support declaration merging, making them ideal for library augmentation and contracts that consumers extend. Type aliases can represent unions, intersections, mapped types, and primitives — things interfaces cannot. Use interface for public API surfaces you expect to be extended, and type for unions and advanced type-level computations." },
      { id: "ts3", subtopic: "Conditional Types", popularity: 9, question: "What are Conditional Types, and how does the `infer` keyword work?", answer: "Conditional types follow T extends U ? X : Y — if T is assignable to U, resolve to X, otherwise Y. The infer keyword captures a type from a pattern inside the condition, like type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never to extract a function's return type. When applied to a union, conditional types distribute over each member automatically." },
      { id: "ts4", subtopic: "Type Guards", popularity: 9, question: "What are Type Guards, and how do you write a custom type guard?", answer: "Type guards narrow a variable's type inside a conditional block. Built-ins include typeof, instanceof, and the in operator. A custom type guard is a function whose return type is a type predicate — function isString(value: unknown): value is string — so TypeScript narrows the variable in the truthy branch. They're essential when working with discriminated unions and untyped API responses." },
      { id: "ts5", subtopic: "Utility Types", popularity: 9, question: "What are the key Utility Types in TypeScript and when do you use them?", answer: "The most commonly used are Partial<T> for update/patch functions, Pick and Omit for shaping subsets of a type, and Record<K, V> for typed dictionaries. More advanced ones like ReturnType<T> and Parameters<T> extract function signatures, and Extract/Exclude filter union members. Interviewers expect you to know how these are implemented internally using mapped and conditional types." },
      { id: "ts6", subtopic: "Mapped Types", popularity: 8, question: "What are Mapped Types and how do you use them to transform existing types?", answer: "Mapped types iterate over the keys of an existing type using { [K in keyof T]: ... } to produce a new type with transformed properties. You can add or remove modifiers like readonly and ? using + or - prefixes. Built-in utility types like Partial, Required, and Readonly are all implemented as mapped types, and the as clause (TS 4.1+) lets you remap keys to generate things like getter-style method signatures." },
      { id: "ts7", subtopic: "Enums vs Unions", popularity: 8, question: "Enums vs. Union Types: which should you prefer and why?", answer: "Enums emit runtime JavaScript objects, which adds bundle size, while string literal unions like type Status = 'active' | 'inactive' are fully erased at compile time with zero runtime overhead. The modern best practice is to prefer string literal unions — they're lighter, more predictable, and integrate better with discriminated unions and exhaustiveness checks." },
      { id: "ts8", subtopic: "Discriminated Unions", popularity: 8, question: "What are Discriminated Unions, and how do they enable exhaustiveness checking?", answer: "A discriminated union is a union of types sharing a common literal property (the discriminant), like type Shape = { kind: 'circle'; radius: number } | { kind: 'square'; side: number }. TypeScript narrows the type automatically in each switch branch. Adding a never assignment in the default case gives you compile-time exhaustiveness checking — if you add a new variant and forget to handle it, the compiler errors." },
      { id: "ts9", subtopic: "Strict Mode", popularity: 7, question: "What does TypeScript's `strict` mode enable, and why is it important?", answer: "The strict flag bundles several checks, the most impactful being strictNullChecks, which makes null and undefined distinct types and eliminates an entire class of runtime errors by forcing you to handle them explicitly. It also enables strictFunctionTypes for contravariant parameter checking and strictPropertyInitialization. Enabling strict from the start is strongly recommended — retrofitting it onto a large codebase surfaces hundreds of latent type errors." },
      { id: "ts10", subtopic: "Module System", popularity: 7, question: "How does TypeScript's module system work, and what is the difference between `import type` and regular `import`?", answer: "import type is a type-only import that is completely erased during compilation, producing no runtime JavaScript — important for avoiding circular dependency issues and reducing bundle size. Since TypeScript 5.0, verbatimModuleSyntax enforces that type-only imports are explicitly marked. Understanding the boundary between type-space and value-space imports is a key signal of senior-level TypeScript fluency." },
    ],
  },
  {
    id: "react",
    label: "React",
    icon: "◎",
    color: "#61dafb",
    questions: [
      { id: "re1", subtopic: "Virtual DOM", popularity: 10, question: "What is the Virtual DOM and how does React's reconciliation algorithm work?", answer: "The Virtual DOM is a lightweight in-memory representation of the real DOM. When state changes, React diffs the new Virtual DOM tree against the previous one using its Fiber-based reconciliation algorithm, using element type and key props to identify what changed. This runs in O(n) time and produces a minimal set of real DOM mutations instead of re-rendering everything." },
      { id: "re2", subtopic: "Hooks", popularity: 10, question: "Explain the rules and internal mechanics of React Hooks. Why can't you call hooks inside conditions or loops?", answer: "React stores hook values as a linked list on each component's Fiber node. On every render, it walks this list in order, so the calling sequence must be identical between renders. If a hook is inside a condition or loop, the call order can change, causing React to map state to the wrong hook — which is why the Rules of Hooks require hooks to always be called at the top level." },
      { id: "re3", subtopic: "Performance", popularity: 9, question: "What is the difference between `useMemo` and `useCallback`, and when should you use each?", answer: "useMemo memoizes a computed value, ideal for expensive calculations like filtering large arrays. useCallback memoizes a function reference, which matters when passing callbacks to child components wrapped in React.memo — since a new function reference on every render would break the memo check. Don't apply either prematurely; the memoization itself has a cost." },
      { id: "re4", subtopic: "Hooks", popularity: 9, question: "How does `useEffect` work, including its cleanup function and dependency array?", answer: "useEffect synchronizes a component with an external system and runs after the browser paints, so it doesn't block the UI. An empty dependency array means it runs only on mount; specific values cause it to re-run when those values change. The cleanup function runs before unmount and before the effect re-executes, preventing memory leaks from subscriptions or timers." },
      { id: "re5", subtopic: "React 18+", popularity: 8, question: "What are React 18's concurrent features, and how do `useTransition` and `startTransition` work?", answer: "React 18's concurrent rendering makes the process interruptible — high-priority updates like typing can pause lower-priority ones like filtering a large list. useTransition returns an isPending flag and a startTransition function that marks state updates as non-urgent, keeping the UI responsive. React 18 also introduced automatic batching, which groups multiple state updates into a single re-render even inside promises and timeouts." },
      { id: "re6", subtopic: "React 18+", popularity: 8, question: "What is React Suspense and how does it relate to code splitting and data fetching?", answer: "Suspense lets components declare they're waiting for async data, showing a fallback UI until ready. Combined with React.lazy(), it enables code splitting with automatic loading states when a chunk hasn't loaded yet. In React 18+, Suspense integrates with streaming SSR so the server can flush HTML progressively, and frameworks like Next.js and TanStack Query use Suspense-compatible data fetching." },
      { id: "re7", subtopic: "Performance", popularity: 8, question: "How do you optimize performance in a React application rendering large datasets?", answer: "For large lists, use windowing libraries like react-window or react-virtuoso to render only visible items, dramatically reducing DOM nodes. React.memo prevents unnecessary re-renders of pure components, and useMemo stabilizes expensive derived data. At the architecture level, colocating state close to where it's used and lazy loading routes with React.lazy are the most impactful structural improvements." },
      { id: "re8", subtopic: "Patterns", popularity: 7, question: "Explain HOCs, render props, and compound components. When would you use each?", answer: "HOCs wrap a component to add behavior like auth or theming, but can lead to wrapper hell — custom hooks have largely replaced them for logic reuse. Compound components like Tabs and Tabs.Panel use React Context internally so related children share implicit state without prop drilling, making them the preferred pattern for flexible UI APIs. Render props are a middle ground but rarely the cleanest solution in modern React." },
      { id: "re9", subtopic: "Hooks", popularity: 7, question: "What is `useRef` and how does it differ from state? What are its common use cases?", answer: "useRef returns a mutable object with a .current property that persists across renders without triggering a re-render when it changes, unlike useState. It's most commonly used to hold a DOM element reference for things like focusing an input, but also works as an instance variable for storing interval IDs or previous values. The key rule is to avoid reading or writing ref.current during rendering itself." },
      { id: "re10", subtopic: "Custom Hooks", popularity: 7, question: "How do you design and build custom hooks, and what principles should guide their architecture?", answer: "Custom hooks are functions prefixed with use that encapsulate reusable stateful logic by composing built-in hooks. A well-designed hook like useFetch or useDebounce follows single responsibility, returns only what the consumer needs, and handles cleanup properly to prevent memory leaks. Keeping the API surface small and using TypeScript generics for type safety are the main design principles." },
    ],
  },
  {
    id: "nodejs",
    label: "Node.js",
    icon: "▣",
    color: "#68a063",
    questions: [
      { id: "nd1", subtopic: "Event Loop", popularity: 10, question: "Explain the Node.js Event Loop and its phases.", answer: "The event loop processes async operations across six phases: Timers, Pending Callbacks, Poll (retrieving new I/O events), Check (setImmediate), and Close Callbacks. Between each phase, Node.js drains the nextTick queue and the microtask queue (Promises), which always run before advancing to the next phase. Misusing this leads to I/O starvation or unexpected execution order." },
      { id: "nd2", subtopic: "Clustering", popularity: 9, question: "What is the difference between Clustering and Worker Threads, and when would you use each?", answer: "The cluster module spawns multiple child processes with isolated memory, ideal for scaling I/O-bound HTTP servers across CPU cores. Worker Threads run within the same process and can share memory via SharedArrayBuffer, making them suited for CPU-intensive tasks like image processing. A practical pattern is to combine both: one cluster process per CPU core, with worker threads inside each process for heavy computation." },
      { id: "nd3", subtopic: "Error Handling", popularity: 9, question: "How do you handle errors properly in a production Node.js application?", answer: "Distinguish operational errors from programmer bugs — operational errors are recoverable, bugs should trigger a controlled shutdown. In async/await code use try/catch; on event emitters always attach error handlers since an unhandled error event crashes the process. Use process.on('unhandledRejection') as a safety net and implement structured logging with pino or winston for production observability." },
      { id: "nd4", subtopic: "Streams", popularity: 8, question: "What is backpressure in Node.js Streams and how do you handle it?", answer: "Backpressure occurs when a readable stream produces data faster than the writable stream can consume it, causing memory to grow unbounded. writable.write() returns false when the internal buffer exceeds highWaterMark, signaling the producer to pause until the drain event fires. The easiest correct solution is stream.pipeline(), which manages backpressure automatically — failing to handle it is one of the most common causes of memory issues in streaming applications." },
      { id: "nd5", subtopic: "Event Loop", popularity: 8, question: "What is the difference between `process.nextTick()` and `setImmediate()`?", answer: "process.nextTick() drains completely between every event loop phase, so it executes before any pending I/O — the risk is that recursive calls can starve I/O entirely. setImmediate() runs in the Check phase, after Poll and pending I/O callbacks. Prefer setImmediate() for deferring work and reserve process.nextTick() for cases where a callback must run before any I/O in the current iteration." },
      { id: "nd6", subtopic: "Security", popularity: 8, question: "What are the key Node.js security vulnerabilities and how do you mitigate them (OWASP)?", answer: "The critical risks are injection attacks, broken authentication, and insecure dependencies. Mitigate with input validation using zod or joi, parameterized queries to prevent injection, the helmet middleware for secure HTTP headers, and regular npm audit runs. Implement rate limiting, avoid eval() and dynamic require(), and follow least-privilege principles for service accounts and environment secrets." },
      { id: "nd7", subtopic: "Middleware", popularity: 8, question: "How does the Express.js middleware pattern work, and what happens if you don't call `next()`?", answer: "Middleware forms a sequential pipeline where each function receives req, res, and next. If next() is never called and no response is sent, the request hangs and the client times out. Error-handling middleware uses the special four-argument signature (err, req, res, next) and is invoked via next(err). Middleware ordering is critical — auth and security middleware must run before route handlers, error handlers must come last." },
      { id: "nd8", subtopic: "Memory", popularity: 7, question: "How do you detect and prevent memory leaks in Node.js?", answer: "Memory leaks most commonly come from forgotten event listeners, uncleaned timers, and closures retaining large objects. Detect them by taking heap snapshots in Chrome DevTools via --inspect or using clinic.js to visualize memory growth over time. Prevent them by using WeakMap for temporary caches, always calling removeListener() when done, and using bounded LRU caches instead of unbounded objects." },
      { id: "nd9", subtopic: "Process Management", popularity: 7, question: "How do you implement graceful shutdown and process management in Node.js?", answer: "Listen for SIGTERM, call server.close() to stop accepting connections, let in-flight requests complete, then close database pools and resources in order. When using PM2, configure kill_timeout and use pm2 reload instead of pm2 restart for zero-downtime deployments. Signal readiness with process.send('ready') when using PM2's wait_ready option so traffic isn't routed before full initialization." },
      { id: "nd10", subtopic: "Internals", popularity: 6, question: "What is the role of `libuv` in Node.js and how does the thread pool work?", answer: "libuv is the C library that provides Node.js with async I/O by abstracting OS-specific APIs like epoll on Linux and IOCP on Windows. It manages a default thread pool of 4 threads (configurable via UV_THREADPOOL_SIZE) for operations that can't be done async at the OS level — like file system calls, dns.lookup(), and some crypto operations. If all threads are busy, thread-pool-dependent operations queue up, which is why cpu-bound crypto can block I/O." },
    ],
  },
  {
    id: "datastructures",
    label: "Data Structures",
    icon: "◈",
    color: "#f97316",
    questions: [
      { id: "ds1", subtopic: "Arrays & Hash Tables", popularity: 10, question: "Two Sum: Find pairs in an array that sum to a target value.", answer: "Use a hash map to store complements as you iterate: for each element, check if the complement (target minus current) already exists in the map. If it does, you found the pair; if not, store the current element. This gives O(n) time and O(n) space, trading memory for a single-pass solution instead of a brute-force O(n²) nested loop." },
      { id: "ds2", subtopic: "Linked Lists", popularity: 9, question: "How do you reverse a singly linked list? Walk through both iterative and recursive approaches.", answer: "The iterative approach uses three pointers — prev, current, and next — walking the list once and redirecting each node's pointer to its predecessor. This runs in O(n) time and O(1) space. The recursive approach reverses from the tail back, but uses O(n) call stack space, making the iterative version preferable in memory-constrained environments." },
      { id: "ds3", subtopic: "Trees (BST)", popularity: 9, question: "How do you validate a Binary Search Tree (BST)?", answer: "Pass min and max bounds down recursively — each node must fall strictly within its allowed range, not just be greater or less than its immediate parent. This is the key insight: a common mistake is only comparing a node to its direct children instead of enforcing the constraint across the entire subtree. The algorithm runs in O(n) time visiting every node once." },
      { id: "ds4", subtopic: "Graphs (BFS/DFS)", popularity: 9, question: "Number of Islands: How do you count connected components in a 2D grid using BFS/DFS?", answer: "Iterate through every cell, and whenever you find an unvisited land cell ('1'), trigger a BFS or DFS to mark all connected land as visited, then increment the island count. The key is marking cells visited as you go to avoid counting them twice. This runs in O(m*n) time since every cell is visited at most once." },
      { id: "ds5", subtopic: "Big O Complexity", popularity: 9, question: "Explain Big O Complexity and compare operations across data structures.", answer: "Big O describes the upper bound of time or space growth as input size increases. Arrays give O(1) random access but O(n) insert/delete; hash tables give O(1) average for search, insert, and delete; balanced BSTs give O(log n) for all operations. Knowing these trade-offs is what drives data structure selection — for example, choosing a hash table for a lookup cache versus a heap for a priority queue." },
      { id: "ds6", subtopic: "Stacks & Queues", popularity: 8, question: "Implement a Stack using Queues (or Queue using Stacks). What are the trade-offs?", answer: "Implementing a stack with two queues makes either push or pop O(n) — you transfer all elements between queues to maintain LIFO order. Similarly, a queue with two stacks amortizes the cost: enqueue to one stack, and when dequeuing, transfer everything to the second stack only when it's empty. These are classic problems testing your understanding of how LIFO and FIFO ordering can be emulated." },
      { id: "ds7", subtopic: "Linked Lists", popularity: 8, question: "How do you detect a cycle in a Linked List? (Floyd's Algorithm)", answer: "Floyd's Tortoise and Hare algorithm uses two pointers: slow advances one node per step, fast advances two. If a cycle exists, they will eventually meet inside it; if fast reaches null, there's no cycle. This runs in O(n) time and O(1) space — no hash set needed — making it the optimal approach for cycle detection." },
      { id: "ds8", subtopic: "Heaps", popularity: 8, question: "How do you find the Kth largest element in an array using a Min-Heap?", answer: "Maintain a min-heap of exactly K elements. As you iterate through the array, if the current element is larger than the heap's minimum root, replace it and heapify. After processing all elements, the root is the Kth largest. This runs in O(n log k) time — far better than sorting the full array at O(n log n) when K is small." },
      { id: "ds9", subtopic: "Graphs (Topological Sort)", popularity: 8, question: "Course Schedule: How do you detect if all courses can be completed (topological sort)?", answer: "Model courses as a directed graph and use Kahn's algorithm: repeatedly remove nodes with zero in-degree, decrementing neighbors' counts. If all nodes are removed, a valid topological order exists; if nodes remain, there's a cycle and not all courses can be completed. This runs in O(V+E) time." },
      { id: "ds10", subtopic: "Tries", popularity: 7, question: "How do you implement an Autocomplete System using a Trie?", answer: "A Trie stores words character by character, so finding all words with a given prefix means traversing to the prefix node, then doing a DFS to collect everything below it. Insertion and prefix search both run in O(m) time where m is the word length. At scale, you pre-compute the top-K suggestions at each node so autocomplete queries don't require a full DFS on every keystroke." },
    ],
  },
  {
    id: "systemdesign",
    label: "System Design",
    icon: "△",
    color: "#a855f7",
    questions: [
      { id: "sd1", subtopic: "URL Shortener", popularity: 10, question: "Design a URL Shortener (e.g., TinyURL, bit.ly)", answer: "Generate a unique short key using Base62 encoding or a hash with collision resolution, store the mapping in a key-value database, and redirect via HTTP 301 or 302. Use Redis to cache hot URLs for sub-50ms lookups since the read-to-write ratio is roughly 100:1. The main design decisions are choosing between pre-generated keys versus on-demand hashing, and whether 301 (permanent, browser-cached) or 302 (temporary, trackable) redirects better fit the use case." },
      { id: "sd2", subtopic: "Chat System", popularity: 9, question: "Design a Chat/Messaging System (e.g., WhatsApp, Messenger)", answer: "Maintain persistent WebSocket connections for real-time delivery. The chat service checks a presence service (backed by Redis) to determine if the recipient is online — if so, deliver via WebSocket; if offline, queue the message and send a push notification. Store message history in Cassandra or HBase for its high write throughput and time-series access patterns." },
      { id: "sd3", subtopic: "Rate Limiter", popularity: 9, question: "Design a Rate Limiter", answer: "Cap API calls per client within a time window and return HTTP 429 when exceeded. The token bucket algorithm is the most practical: it allows controlled bursts while enforcing an average rate. Store counters in Redis for sub-millisecond atomic increments using INCR with TTL. Implement at the API gateway layer so every downstream service gets protection without duplicating logic." },
      { id: "sd4", subtopic: "News Feed", popularity: 9, question: "Design a Social Media News Feed (e.g., Facebook, Twitter)", answer: "Fan-out-on-write pre-computes each user's feed on post, enabling fast reads but expensive writes for users with millions of followers. The optimal approach is a hybrid: push to regular users' feed caches on write, but pull celebrity posts at read time to avoid fan-out storms. A ranking service then applies relevance scoring before serving the final feed." },
      { id: "sd5", subtopic: "Notification System", popularity: 8, question: "Design a Notification System", answer: "Decouple triggering from delivery: the notification service validates and enriches the request, checks user preferences, then publishes to prioritized Kafka topics. Channel workers (APNs/FCM for push, SES for email, Twilio for SMS) consume independently and handle retries. Failed deliveries go to a dead letter queue for inspection and reprocessing." },
      { id: "sd6", subtopic: "Database Sharding", popularity: 7, question: "Design Database Sharding", answer: "Shard key selection is the most critical decision — a good key distributes load evenly and keeps related queries on one shard to avoid cross-shard joins. Consistent hashing with virtual nodes is the standard approach because adding or removing a shard only moves approximately 1/N of the data instead of reshuffling everything. Directory-based sharding adds flexibility at the cost of a lookup service becoming a bottleneck." },
      { id: "sd7", subtopic: "File Storage", popularity: 7, question: "Design a File Storage System (e.g., Google Drive, Dropbox)", answer: "Split files into chunks (typically ~4MB), identify each by content hash for deduplication and delta sync, and store chunks in object storage like S3. File metadata — hierarchy, permissions, versions — lives in a relational database. A sync service uses WebSockets or long polling to notify connected devices of changes in real time." },
      { id: "sd8", subtopic: "Search Autocomplete", popularity: 7, question: "Design a Search Autocomplete / Typeahead System", answer: "The core data structure is a Trie with pre-computed top-K suggestions at each node, held in memory for microsecond lookups. At scale, partition the trie via range-based sharding across servers, and decouple reads from updates — queries hit the in-memory trie while search log aggregation pipelines rebuild and atomically swap in updated tries. Cache popular prefixes aggressively at the CDN edge." },
      { id: "sd9", subtopic: "CDN", popularity: 6, question: "Design a CDN (Content Delivery Network)", answer: "Geographically distributed edge servers cache content close to users, with DNS geo-routing directing each request to the nearest edge PoP. On a cache hit, the edge serves directly in under 10ms. On a miss, it fetches from a shield cache or the origin, caches the response with a TTL, and serves it. Invalidation is handled via TTL expiry, versioned URLs, or a purge API for urgent updates." },
      { id: "sd10", subtopic: "Load Balancer", popularity: 6, question: "Design a Load Balancer", answer: "Load balancers operate at Layer 4 (TCP — fast, IP/port based) or Layer 7 (HTTP — smart, can route by URL path or headers). Least connections and consistent hashing are the most useful algorithms: least connections routes to the least busy server, while consistent hashing enables sticky sessions without centralized state. Health checks continuously probe backends and remove unhealthy instances from the pool automatically." },
    ],
  },
  {
    id: "mycareer",
    label: "My Career",
    icon: "★",
    color: "#E8A838",
    questions: [
      { id: "cv1", subtopic: "RAG & AI Systems", popularity: 10, question: "You mention building RAG systems with pgVector and Qdrant. Walk me through the full pipeline — from document ingestion to semantic retrieval. What chunking strategy did you use and why?", answer: "At Lex Consultoria, I built a RAG pipeline on top of TOTVS ERP data: documents are chunked using a sliding window with 50-token overlap to preserve context across boundaries, embedded with OpenAI's text-embedding-ada-002, and stored in pgVector — I chose pgVector because the HR data already lived in PostgreSQL, avoiding an extra infrastructure dependency. At query time, the user's question is embedded and a cosine similarity search retrieves the top-k chunks, which are injected into the GPT-4 prompt as grounded context. At TateAI I used Qdrant instead because we needed faster similarity search at scale with metadata filtering." },
      { id: "cv2", subtopic: "System Architecture", popularity: 10, question: "At BTG Pactual you processed $10M+ daily transactions. How did you architect the system for reliability at that scale? What happens when a downstream service fails?", answer: "The system was built on AWS Lambda, DynamoDB, and Kafka — each transaction publishes to a Kafka topic and downstream consumers process independently, so a failure in one consumer doesn't block others. For financial reliability, we used idempotency keys to prevent duplicate transactions on retries and DLQs for failed events. Circuit breakers prevented cascading failures and we achieved 99.9% uptime at 200ms average latency." },
      { id: "cv3", subtopic: "Real-time Systems", popularity: 9, question: "You handled 1000+ concurrent WebSocket connections for chat streaming at TateAI. How did you manage connection lifecycle, backpressure, and scaling?", answer: "A connection registry tracked user sessions, handled heartbeats, and cleaned up on disconnect. For LLM streaming backpressure, I forwarded tokens to the client as they arrived from the LLM API, and paused the upstream read when the client's buffer was full. Scaling used multiple Node.js instances behind a load balancer with sticky sessions and Redis pub/sub to broadcast messages across instances." },
      { id: "cv4", subtopic: "Migration & Optimization", popularity: 9, question: "You led migrating Java services to Node.js at BTG Pactual, reducing costs by 35%. How did you approach this migration without downtime?", answer: "I used the strangler fig pattern — building the Node.js replacement alongside the Java service, then using API Gateway weighted routing to shift traffic gradually: 10%, 25%, 50%, 100% while monitoring error rates and latency. Cost savings came from Lambda's pay-per-invocation model versus always-on ECS containers, and response times improved 45% because Node.js handles I/O-bound workloads more efficiently." },
      { id: "cv5", subtopic: "Telemedicine Platform", popularity: 9, question: "Tell me about the telemedicine platform at Lex Consultoria. How did you handle video call reliability, medical data security, and serving 20,000+ employees?", answer: "We self-hosted Jitsi for data sovereignty and implemented automatic quality adaptation with fallback to audio-only and reconnection with session persistence for reliability. Medical data follows LGPD: AES-256 encryption at rest, TLS 1.3 in transit, S3 bucket policies with access logging for audit. The React frontend uses WebSockets for real-time presence, with role-based access control covering all 20,000+ employees." },
      { id: "cv6", subtopic: "AI-Assisted Development", popularity: 8, question: "You claim shipping features 3x faster using AI-assisted development tools. Can you give a concrete example? How do you ensure code quality?", answer: "Building a financial report module at BTG that would normally take two weeks took three days using Claude Code for architecture scaffolding, Copilot for boilerplate, and Amazon Q for AWS configurations. Quality assurance is critical — I never accept AI output blindly: I review every line for security issues, verify business logic matches requirements, and run the full test suite before any PR is opened." },
      { id: "cv7", subtopic: "E-commerce & Performance", popularity: 8, question: "At FAVO you achieved 60% latency reduction. What specific optimizations did you make?", answer: "Distributed tracing revealed two main issues: N+1 query problems in order creation, fixed with DataLoader-style batching and denormalization into DynamoDB; and Lambda cold starts on critical paths, fixed with provisioned concurrency and reduced package sizes. Non-critical external service calls moved from synchronous to SQS-backed async. Combined, these dropped P95 latency from ~2.5s to ~1s and improved conversion rate by 35%." },
      { id: "cv8", subtopic: "Leadership", popularity: 8, question: "As a Tech Lead at Lex, how do you balance hands-on coding with leadership responsibilities?", answer: "I allocate roughly 60% coding and 40% leadership — code reviews, mentoring, planning, and stakeholder communication. For architectural decisions I write lightweight ADRs, present options with trade-offs, and take ownership of the outcome. Staying close to the code keeps me honest about estimates and means I can jump in directly during critical production situations." },
      { id: "cv9", subtopic: "Anomaly Detection", popularity: 7, question: "How does your anomaly detection system with Gemini work for time-tracking at Lex?", answer: "The system feeds structured time-tracking data from TOTVS ERP to Gemini with a carefully engineered prompt defining anomaly categories and requesting confidence scores. To control false positives, I only flag items above 80% confidence and cross-reference against known exceptions like approved overtime and shift workers before surfacing anything to managers. This saves 20+ hours per week of manual review that previously required an HR analyst." },
      { id: "cv10", subtopic: "Serverless Architecture", popularity: 8, question: "You've used AWS Lambda extensively. What are the real-world limitations you've hit, and how did you work around them?", answer: "Cold starts on financial APIs were solved with provisioned concurrency; the 15-minute execution limit on document processing was solved by orchestrating multi-step workflows with Step Functions. For PostgreSQL connection management I used RDS Proxy to avoid exhausting connection limits at scale. I kept business logic in framework-agnostic modules with thin Lambda handlers to limit vendor lock-in — this architecture handled 100,000+ daily requests at 99.95% availability at FAVO." },
    ],
  },
];

export const uid = () => Math.random().toString(36).slice(2, 9);

export function buildPrompt(topic, subtopic, count) {
  return `You are a senior software engineer preparing interview questions for developers specialising in TypeScript, React, and Node.js.

Generate exactly ${count} high-quality technical interview questions with detailed answers for the following:
- Topic: ${topic}
- Subtopic: ${subtopic}

Requirements:
- Questions should range from mid to senior level.
- Answers must be detailed (3–5 sentences minimum), accurate, and mention real-world usage.
- Include code snippets or examples where relevant (use plain text, no markdown fences).
- Cover different angles: conceptual understanding, practical usage, trade-offs.

Respond ONLY with a valid JSON array. No preamble, no markdown, no backticks.
Format:
[
  {
    "question": "...",
    "answer": "..."
  }
]`;
}
