export const SEED_TOPICS = [
  {
    id: "backend",
    label: "Backend Fundamentals",
    icon: "⚙",
    color: "#E8A838",
    questions: [
      { id: "be1", subtopic: "API Design", popularity: 9, question: "How do you design a RESTful API with proper versioning, idempotency, and error responses?", answer: "A well-designed REST API uses plural nouns for resource endpoints (/api/v1/users), proper HTTP methods (GET, POST, PUT, PATCH, DELETE), and meaningful status codes (201 Created, 404 Not Found, 422 Unprocessable Entity). URI-based versioning (/v1/, /v2/) is the most common production approach because it is explicit and easy to debug. For payment or mutation endpoints, require an idempotency key header so that retried requests return the previously stored result instead of duplicating side effects. Error responses should follow a consistent schema (e.g., { error: { code, message, details } }) and never leak stack traces or internal implementation details in production." },
      { id: "be2", subtopic: "Authentication", popularity: 9, question: "How do you implement authentication and authorization using JWT and OAuth 2.0?", answer: "JWT (JSON Web Token) is used for stateless authentication: the server issues a signed token containing user claims upon login, and the client sends it via the Authorization: Bearer header on subsequent requests. Access tokens should be short-lived (15-30 minutes) with longer-lived refresh tokens stored in HTTP-only cookies to mitigate XSS attacks. OAuth 2.0 is an authorization framework that delegates authentication to a third-party provider (Google, GitHub) using flows like Authorization Code with PKCE for web apps. In a Node.js/Express stack, middleware validates the JWT signature, checks expiration, and attaches the decoded user to req.user before the route handler runs. Secrets should be managed via environment variables or a dedicated secret manager (AWS Secrets Manager, HashiCorp Vault), never hardcoded." },
      { id: "be3", subtopic: "Design Patterns", popularity: 8, question: "How do you implement the Circuit Breaker pattern in a microservices architecture?", answer: "The Circuit Breaker pattern prevents cascading failures by wrapping calls to external services with failure tracking: after a configured threshold of consecutive failures, the circuit 'opens' and immediately rejects requests without calling the downstream service. After a cooldown period, it enters a 'half-open' state and allows a limited number of test requests through; if those succeed, the circuit closes again. In Node.js, libraries like opossum provide a ready-made implementation. This should be combined with exponential backoff plus random jitter on retries to avoid retry storms where all clients retry simultaneously." },
      { id: "be4", subtopic: "Error Handling", popularity: 9, question: "How do you handle centralized error handling in a Node.js/Express application?", answer: "In Express, centralized error handling uses a four-parameter middleware (err, req, res, next) registered after all route definitions. All async route handlers should wrap their logic in try/catch blocks and forward errors via next(err), or use a wrapper function like asyncHandler that catches rejected promises automatically. The error middleware should distinguish between operational errors (expected, like validation failures) and programmer errors (unexpected, like null reference), logging the full stack for the latter while returning a sanitized response to the client. For production, use process.on('unhandledRejection') and process.on('uncaughtException') as safety nets with graceful shutdown logic." },
      { id: "be5", subtopic: "Caching", popularity: 8, question: "What caching strategies do you use, and how do you handle cache invalidation?", answer: "The most common strategies are Cache-Aside (application checks cache first, falls back to DB, then populates cache), Write-Through (writes go to cache and DB simultaneously), and Write-Behind (writes go to cache first, DB is updated asynchronously). Redis is the standard in-memory cache for Node.js backends, used for session storage, rate limiting, and frequently-read data. Cache invalidation is handled via TTL (time-to-live) expiration, event-driven invalidation (publish a message when data changes), or versioned cache keys. Set explicit Cache-Control and ETag headers for HTTP caching, and use conditional requests (If-None-Match) for revalidation." },
      { id: "be6", subtopic: "Databases", popularity: 8, question: "How do you design database schemas and optimize queries for a production application?", answer: "Schema design starts with understanding access patterns: use normalized relational schemas (PostgreSQL) when data integrity and complex joins are critical, and denormalized document schemas (MongoDB) when read performance and flexible schemas matter more. Indexing is the primary optimization tool — create composite indexes that match your most frequent query patterns and use EXPLAIN ANALYZE to identify slow queries. For pagination, cursor-based pagination (using a stable reference like an auto-increment ID or timestamp) outperforms offset-based pagination on large datasets. Use connection pooling (e.g., pg-pool for PostgreSQL, Prisma's built-in pool) to avoid the overhead of establishing new connections per request." },
      { id: "be7", subtopic: "Microservices", popularity: 7, question: "How do you implement graceful shutdown in a Node.js service?", answer: "Graceful shutdown ensures zero dropped requests during deployments: listen for SIGTERM (sent by Kubernetes, Docker, or PM2), stop accepting new connections by calling server.close(), allow in-flight requests to complete within a configurable timeout (e.g., 30 seconds), then close database pools, Redis connections, and message queue consumers in order. If in-flight requests exceed the timeout, force-exit with process.exit(1) to prevent the process from hanging indefinitely. Health check endpoints (/healthz, /readyz) should reflect the shutdown state so load balancers stop routing traffic to the draining instance." },
      { id: "be8", subtopic: "Design Patterns", popularity: 7, question: "How do you implement Dependency Injection in a Node.js/TypeScript application?", answer: "Dependency Injection (DI) is a pattern where a class or function receives its dependencies as constructor or function parameters rather than creating them internally, enabling loose coupling and easy unit testing with mock implementations. In TypeScript, frameworks like tsyringe, InversifyJS, or NestJS's built-in DI container use decorators (@injectable(), @inject()) and reflection metadata to automatically resolve and inject dependencies at runtime. Even without a framework, manual DI through constructor injection is effective: define interfaces for your services, inject concrete implementations at the composition root, and swap them for test doubles in tests." },
    ],
  },
  {
    id: "typescript",
    label: "TypeScript",
    icon: "◇",
    color: "#3178c6",
    questions: [
      { id: "ts1", subtopic: "Generics", popularity: 10, question: "How do Generics work in TypeScript, and how do you constrain them?", answer: "Generics allow you to write reusable, type-safe code by parameterizing types, so a function or class can work with multiple types without losing type information. You constrain generics using the extends keyword, e.g., <T extends { length: number }>, which ensures the type argument satisfies a minimum shape. This is fundamentally different from using any because the compiler still tracks and enforces the actual type throughout the function body and at the call site. A practical example is writing a generic merge function: function merge<T extends object, U extends object>(a: T, b: U): T & U." },
      { id: "ts2", subtopic: "Type System", popularity: 10, question: "Explain the difference between `type` and `interface`. When would you use one over the other?", answer: "Interfaces support declaration merging (multiple declarations with the same name are automatically combined), making them ideal for library augmentation and defining contracts that consumers may extend. Type aliases can represent unions, intersections, mapped types, conditional types, and primitives — things interfaces cannot. A practical rule: use interface for public API surfaces and object shapes you expect to be extended; use type for unions, computed types, and when you need advanced type-level operations. In performance terms, interfaces are also slightly faster for the compiler to check due to caching." },
      { id: "ts3", subtopic: "Conditional Types", popularity: 9, question: "What are Conditional Types, and how does the `infer` keyword work?", answer: "Conditional types follow the syntax T extends U ? X : Y, which means 'if T is assignable to U, resolve to X, otherwise Y.' The infer keyword is used inside the condition clause to capture (extract) a type from a pattern: for example, type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never extracts the return type of a function. When conditional types receive a union as T, they distribute over each member automatically, evaluating the condition for each union member individually. This is a core building block for advanced type utilities." },
      { id: "ts4", subtopic: "Type Guards", popularity: 9, question: "What are Type Guards, and how do you write a custom type guard?", answer: "Type guards are expressions that narrow a variable's type within a conditional block. Built-in guards include typeof (for primitives), instanceof (for class instances), and the in operator (for property checks). A custom type guard is a function whose return type is a type predicate: function isString(value: unknown): value is string { return typeof value === 'string'; }. When this function returns true, TypeScript narrows the variable to string in the truthy branch. Custom type guards are essential when working with discriminated unions and API responses." },
      { id: "ts5", subtopic: "Utility Types", popularity: 9, question: "What are the key Utility Types in TypeScript and when do you use them?", answer: "The most commonly used are: Partial<T> (makes all properties optional, ideal for update/patch functions), Required<T> (makes all properties required), Pick<T, K> (extracts a subset of properties), Omit<T, K> (removes specified properties), and Record<K, V> (creates an object type with keys of type K and values of type V). More advanced ones include Extract<T, U> and Exclude<T, U> which filter union members, and ReturnType<T> and Parameters<T> which extract function signatures. Interviewers expect you to know how they are implemented internally using mapped and conditional types." },
      { id: "ts6", subtopic: "Mapped Types", popularity: 8, question: "What are Mapped Types and how do you use them to transform existing types?", answer: "Mapped types iterate over the keys of an existing type to produce a new type with transformed properties, using the syntax { [K in keyof T]: ... }. You can add or remove modifiers like readonly and ? using + or - prefixes. Built-in utility types like Partial<T>, Required<T>, Readonly<T>, and Record<K, V> are all implemented as mapped types internally. You can also remap keys using the as clause (TS 4.1+): { [K in keyof T as `get${Capitalize<K & string>}`]: () => T[K] } to generate getter-style method signatures." },
      { id: "ts7", subtopic: "Enums vs Unions", popularity: 8, question: "Enums vs. Union Types: which should you prefer and why?", answer: "Numeric enums generate runtime JavaScript objects with reverse mappings, which adds to bundle size. String enums are safer but still emit runtime code. Union types of string literals (e.g., type Status = 'active' | 'inactive') produce zero runtime overhead since they are erased during compilation, and they work naturally with type narrowing and exhaustiveness checks. The modern best practice is to prefer string literal unions for most use cases — they are lighter, more predictable, and integrate better with discriminated unions." },
      { id: "ts8", subtopic: "Discriminated Unions", popularity: 8, question: "What are Discriminated Unions, and how do they enable exhaustiveness checking?", answer: "A discriminated union is a union of types that share a common literal property (the 'discriminant'), such as type Shape = { kind: 'circle'; radius: number } | { kind: 'square'; side: number }. When you switch on the discriminant property, TypeScript narrows the type in each branch automatically. Exhaustiveness checking is achieved by assigning the narrowed value to never in the default case: if you add a new variant but forget to handle it, the assignment to never produces a compile-time error. This pattern is widely used for state machines, Redux actions, and API response handling." },
      { id: "ts9", subtopic: "Strict Mode", popularity: 7, question: "What does TypeScript's `strict` mode enable, and why is it important?", answer: "The strict flag enables: strictNullChecks (null/undefined are distinct types), strictFunctionTypes (contravariant parameter checking), strictBindCallApply (type-safe bind/call/apply), strictPropertyInitialization (class properties must be initialized), and noImplicitAny. The most impactful is strictNullChecks, which eliminates an entire class of runtime errors by forcing you to handle null/undefined explicitly. Enabling strict mode from the start is strongly recommended; retrofitting it onto a large codebase surfaces hundreds of latent type errors." },
      { id: "ts10", subtopic: "Module System", popularity: 7, question: "How does TypeScript's module system work, and what is the difference between `import type` and regular `import`?", answer: "TypeScript supports ES modules (import/export) as the standard module system. import type { Foo } from './bar' is a type-only import that is completely erased during compilation, producing no runtime JavaScript — this is important for avoiding circular dependency issues and reducing bundle size. Since TypeScript 5.0, verbatimModuleSyntax enforces that type-only imports are explicitly marked. Understanding the difference between type-space and value-space imports is a key signal of senior-level TypeScript fluency." },
    ],
  },
  {
    id: "react",
    label: "React",
    icon: "◎",
    color: "#61dafb",
    questions: [
      { id: "re1", subtopic: "Virtual DOM", popularity: 10, question: "What is the Virtual DOM and how does React's reconciliation algorithm work?", answer: "The Virtual DOM is a lightweight in-memory representation of the real DOM. When state changes, React creates a new Virtual DOM tree and diffs it against the previous one using its reconciliation algorithm (powered by the Fiber architecture). React compares elements by type and uses key props to identify which items in a list have changed, been added, or removed. This diffing process runs in O(n) time by making two assumptions: elements of different types produce different trees, and keys provide hints about stable identity. The result is a minimal set of real DOM mutations." },
      { id: "re2", subtopic: "Hooks", popularity: 10, question: "Explain the rules and internal mechanics of React Hooks. Why can't you call hooks inside conditions or loops?", answer: "React stores hook values as a linked list attached to the memoizedState property of each component's Fiber node. On every render, React walks this list in order, so the calling sequence of hooks must be identical between renders. If you place a hook inside a condition or loop, you risk changing the call order, which causes React to map the wrong state to the wrong hook. This is why the Rules of Hooks mandate that hooks are always called at the top level of a function component or custom hook." },
      { id: "re3", subtopic: "Performance", popularity: 9, question: "What is the difference between `useMemo` and `useCallback`, and when should you use each?", answer: "useMemo memoizes a computed value and only recalculates when its dependencies change, ideal for expensive computations like filtering large arrays. useCallback memoizes a function reference, ensuring the same function object is returned across renders unless dependencies change. useCallback(fn, deps) is essentially equivalent to useMemo(() => fn, deps). Use useCallback when passing callbacks to child components wrapped in React.memo. Don't apply either hook prematurely — the memoization itself has a cost." },
      { id: "re4", subtopic: "Hooks", popularity: 9, question: "How does `useEffect` work, including its cleanup function and dependency array?", answer: "useEffect lets you synchronize a component with an external system (API calls, subscriptions, DOM manipulation). It runs after the browser paints, so it does not block the UI. The dependency array controls when the effect re-runs: an empty array [] means it runs only on mount, specific values mean it re-runs when those values change. The cleanup function runs before the component unmounts and before the effect re-executes, essential for preventing memory leaks from subscriptions or timers. A common mistake is including object/array references that change on every render, leading to infinite loops." },
      { id: "re5", subtopic: "React 18+", popularity: 8, question: "What are React 18's concurrent features, and how do `useTransition` and `startTransition` work?", answer: "React 18 introduced concurrent rendering, making the rendering process interruptible — React can pause, resume, or abandon a render based on priority. useTransition returns an isPending flag and a startTransition function that marks state updates as non-urgent. This means high-priority updates (like typing in an input) can interrupt lower-priority transitions (like filtering a large list), keeping the UI responsive. Automatic batching in React 18 also groups multiple state updates into a single re-render, even inside promises and timeouts." },
      { id: "re6", subtopic: "React 18+", popularity: 8, question: "What is React Suspense and how does it relate to code splitting and data fetching?", answer: "Suspense lets components declare that they are waiting for asynchronous data before they can render, showing a fallback UI (like a spinner) in the meantime. For code splitting, React.lazy() combined with <Suspense> allows dynamic imports and loading states until the chunk has loaded. In React 18+, Suspense integrates with concurrent features and streaming SSR, allowing the server to flush HTML progressively. Frameworks like Next.js and TanStack Query use Suspense-compatible data fetching." },
      { id: "re7", subtopic: "Performance", popularity: 8, question: "How do you optimize performance in a React application rendering large datasets?", answer: "For large lists (10,000+ items), windowing/virtualization libraries like react-window or react-virtuoso render only the visible items in the viewport, dramatically reducing DOM nodes. Use React.memo to prevent re-renders of pure components, useMemo for expensive derived data, and useCallback to stabilize function references. Proper use of key props ensures React correctly identifies which list items changed. At the architecture level, colocating state close to where it is used, splitting context providers, and lazy loading routes with React.lazy are all critical strategies." },
      { id: "re8", subtopic: "Patterns", popularity: 7, question: "Explain HOCs, render props, and compound components. When would you use each?", answer: "Higher-Order Components (HOCs) are functions that take a component and return a new one with enhanced behavior (e.g., withAuth, withTheme); they were the primary reuse mechanism before hooks but can lead to wrapper hell. Render props pass a function as a prop that the component calls with its internal state. Compound components (like <Tabs>, <Tabs.Panel>) use React Context internally so related child components share implicit state without prop drilling. In modern React, custom hooks have largely replaced HOCs and render props for logic reuse, but compound components remain preferred for flexible UI APIs." },
      { id: "re9", subtopic: "Hooks", popularity: 7, question: "What is `useRef` and how does it differ from state? What are its common use cases?", answer: "useRef returns a mutable object with a .current property that persists across renders without triggering a re-render when it changes, unlike useState. Its most common use case is holding a reference to a DOM element (e.g., to focus an input or measure dimensions), but it is also used as an 'instance variable' to store interval IDs, previous state values, or flags. Because updating a ref does not schedule a re-render, it is useful for tracking values in event handlers or effects. A key rule is to avoid reading or writing ref.current during rendering itself." },
      { id: "re10", subtopic: "Custom Hooks", popularity: 7, question: "How do you design and build custom hooks, and what principles should guide their architecture?", answer: "Custom hooks are functions prefixed with use that encapsulate reusable stateful logic by composing built-in hooks. A well-designed custom hook (e.g., useFetch, useDebounce, useLocalStorage) should follow the single responsibility principle, returning only the state and actions the consumer needs. They should handle cleanup properly in their effects to prevent memory leaks. Custom hooks enable you to extract and test complex logic independently from the UI component. When designing them, keep the API surface small and use TypeScript generics for type safety." },
    ],
  },
  {
    id: "nodejs",
    label: "Node.js",
    icon: "▣",
    color: "#68a063",
    questions: [
      { id: "nd1", subtopic: "Event Loop", popularity: 10, question: "Explain the Node.js Event Loop and its phases.", answer: "The Node.js event loop is a single-threaded mechanism that processes asynchronous operations across six phases: Timers (executes setTimeout/setInterval callbacks), Pending Callbacks (deferred I/O), Idle/Prepare (internal), Poll (retrieves new I/O events), Check (setImmediate callbacks), and Close Callbacks. Between each phase, Node.js drains the nextTickQueue (from process.nextTick()) and the microtask queue (Promises), which always run before moving to the next phase. Understanding this is critical because misusing it leads to starvation of I/O operations or unexpected execution order." },
      { id: "nd2", subtopic: "Clustering", popularity: 9, question: "What is the difference between Clustering and Worker Threads, and when would you use each?", answer: "The cluster module spawns multiple child processes, each with its own V8 instance, event loop, and isolated memory space — ideal for scaling I/O-bound HTTP servers across all CPU cores. Worker Threads run within the same process and can share memory via SharedArrayBuffer, making them suited for CPU-intensive tasks like image processing or data parsing. A practical pattern is to combine both: use clustering to spawn one process per CPU core, and within each process use worker threads for heavy computation. Cluster workers are fully isolated (a crash in one does not affect others), while worker threads share the process." },
      { id: "nd3", subtopic: "Error Handling", popularity: 9, question: "How do you handle errors properly in a production Node.js application?", answer: "Node.js distinguishes between operational errors (expected, recoverable like failed network requests) and programmer errors (bugs like TypeError). In async/await code, use try/catch blocks; in event emitters, always attach 'error' handlers (an unhandled error event crashes the process); and use process.on('unhandledRejection') and process.on('uncaughtException') as safety nets for logging before a controlled shutdown. Senior developers should implement structured logging (e.g., with pino or winston), use circuit breakers for external service calls, and design for graceful degradation." },
      { id: "nd4", subtopic: "Streams", popularity: 8, question: "What is backpressure in Node.js Streams and how do you handle it?", answer: "Backpressure occurs when a readable stream produces data faster than the writable stream can consume it, which can lead to excessive memory usage. The writable.write() method returns false when the internal buffer exceeds highWaterMark, signaling that the producer should pause. The proper way to handle it is to listen for the 'drain' event on the writable stream before resuming the readable stream, or better yet, use stream.pipeline() which manages backpressure automatically. Failing to handle backpressure is one of the most common causes of memory issues in production streaming applications." },
      { id: "nd5", subtopic: "Event Loop", popularity: 8, question: "What is the difference between `process.nextTick()` and `setImmediate()`?", answer: "process.nextTick() queues a callback in the nextTick queue, which is drained completely between every phase of the event loop, making it execute before any pending I/O. setImmediate() schedules a callback in the Check phase, meaning it executes after the Poll phase and after pending I/O callbacks. The danger of process.nextTick() is that recursive calls can starve I/O because the event loop cannot advance until the nextTick queue is empty. Generally prefer setImmediate() for deferring work and reserve process.nextTick() for cases where you need to ensure a callback runs before any I/O." },
      { id: "nd6", subtopic: "Security", popularity: 8, question: "What are the key Node.js security vulnerabilities and how do you mitigate them (OWASP)?", answer: "The most critical risks include injection attacks (SQL/NoSQL injection, XSS), broken authentication, and insecure dependencies. Mitigations include: validating and sanitizing input with zod or joi, using parameterized queries, setting secure HTTP headers with helmet middleware, enforcing HTTPS, and running npm audit regularly. Avoid eval() and dynamic require(), implement rate limiting, use CSRF tokens for state-changing operations, and follow the principle of least privilege. Familiarity with the OWASP Node.js Security Cheat Sheet is expected at senior level." },
      { id: "nd7", subtopic: "Middleware", popularity: 8, question: "How does the Express.js middleware pattern work, and what happens if you don't call `next()`?", answer: "Middleware functions in Express form a sequential pipeline where each function receives req, res, and next arguments. If next() is never called and no response is sent, the request hangs indefinitely and the client eventually times out. Error-handling middleware has a special four-argument signature (err, req, res, next) and is invoked when next(err) is called with an argument. Middleware ordering matters critically — for example, placing helmet() or authentication middleware before route handlers, and error-handling middleware last in the stack." },
      { id: "nd8", subtopic: "Memory", popularity: 7, question: "How do you detect and prevent memory leaks in Node.js?", answer: "Memory leaks commonly stem from forgotten global references, uncleaned event listeners, uncleared timers/intervals, closures retaining large objects, and growing caches without eviction. Detect them by monitoring process.memoryUsage() over time, taking heap snapshots with Chrome DevTools (via --inspect flag), or using clinic.js. To prevent leaks, use WeakMap/WeakSet for temporary caches, always call removeListener() when done, set maxListeners to catch accidental accumulation, and use bounded caches (e.g., LRU cache). In production, PM2 can restart a process when memory exceeds a threshold." },
      { id: "nd9", subtopic: "Process Management", popularity: 7, question: "How do you implement graceful shutdown and process management in Node.js?", answer: "Listen for SIGTERM/SIGINT signals, call server.close() to stop accepting new connections, allow in-flight requests to complete, close database pools and resources, and set a forced-exit timeout as a fallback. When using PM2, configure kill_timeout and use pm2 reload instead of pm2 restart for zero-downtime deployments. Signal readiness with process.send('ready') when using PM2's wait_ready option, ensuring traffic is not routed before full initialization." },
      { id: "nd10", subtopic: "Internals", popularity: 6, question: "What is the role of `libuv` in Node.js and how does the thread pool work?", answer: "libuv is the C library that provides Node.js with its async I/O model by abstracting OS-specific APIs (epoll on Linux, kqueue on macOS, IOCP on Windows). It manages the event loop and a default thread pool of 4 threads (configurable via UV_THREADPOOL_SIZE, max 1024) for operations that cannot be done asynchronously at the OS level — such as dns.lookup(), file system operations, and some crypto functions. If all thread pool threads are busy, other thread-pool-dependent operations queue up. Know which APIs use the thread pool vs native OS async (e.g., dns.resolve() uses c-ares, not the thread pool)." },
    ],
  },
  {
    id: "datastructures",
    label: "Data Structures",
    icon: "◈",
    color: "#f97316",
    questions: [
      { id: "ds1", subtopic: "Arrays & Hash Tables", popularity: 10, question: "Two Sum: Find pairs in an array that sum to a target value.", answer: "Given an array and a target sum, find two numbers that add up to the target. The optimal solution uses a hash table to store complements as you iterate, achieving O(n) time and O(n) space. This tests understanding of hash map lookups and trade-offs between time and space complexity.\n\n  ARRAY: [2, 7, 11, 15]  TARGET = 9\n\n  Step-by-step with Hash Map:\n  +-------+----------+------------+\n  | Index | Element  | Complement |\n  +-------+----------+------------+\n  |   0   |    2     |    7       |\n  |   1   |    7     | 2 (FOUND!) |\n  +-------+----------+------------+\n\n  Hash Map: { 2: idx 0 }\n  Result: indices [0, 1]" },
      { id: "ds2", subtopic: "Linked Lists", popularity: 9, question: "How do you reverse a singly linked list? Walk through both iterative and recursive approaches.", answer: "Reversing a singly linked list requires manipulating pointers so each node points to its predecessor. The iterative approach uses three pointers (prev, current, next) and runs in O(n) time with O(1) space.\n\n  BEFORE:\n  1 --> 2 --> 3 --> NULL\n\n  DURING (pointer manipulation):\n  prev    curr    next\n  NULL <-- 1       2 --> 3 --> NULL\n\n  AFTER:\n  NULL <-- 1 <-- 2 <-- 3\n                         ^ new head" },
      { id: "ds3", subtopic: "Trees (BST)", popularity: 9, question: "How do you validate a Binary Search Tree (BST)?", answer: "To validate a BST, confirm that every node's value falls within an allowed range: left children must be less than the parent, and right children must be greater. Pass min/max bounds down recursively, achieving O(n) time. A common mistake is only checking immediate children rather than enforcing the constraint across the entire subtree.\n\n  VALID BST:          INVALID BST:\n       8                   8\n      / \\                 / \\\n     4   10               4   10\n    / \\    \\             / \\    \\\n   2   6   12           2   12    9\n                              ^\n  Validation bounds:    12 > 8 but is in\n  Node 6: min=4, max=8  left subtree --> INVALID" },
      { id: "ds4", subtopic: "Graphs (BFS/DFS)", popularity: 9, question: "Number of Islands: How do you count connected components in a 2D grid using BFS/DFS?", answer: "Given a 2D grid of '1's (land) and '0's (water), count islands. Iterate through each cell and trigger BFS/DFS whenever an unvisited '1' is found, marking all connected land cells as visited. Runs in O(m*n) time.\n\n  INPUT GRID:          DFS TRAVERSAL:\n  1 1 0 0 0            X X 0 0 0\n  1 1 0 0 0            X X 0 0 0\n  0 0 1 0 0    --->    0 0 X 0 0\n  0 0 0 1 1            0 0 0 X X\n\n  RESULT: 3 islands\n  Island 1: {(0,0),(0,1),(1,0),(1,1)}\n  Island 2: {(2,2)}\n  Island 3: {(3,3),(3,4)}" },
      { id: "ds5", subtopic: "Big O Complexity", popularity: 9, question: "Explain Big O Complexity and compare operations across data structures.", answer: "Big O describes the upper bound of time/space growth as input increases. You must compare complexities and justify trade-offs.\n\n  +------------------+--------+--------+--------+--------+\n  | Data Structure   | Access | Search | Insert | Delete |\n  +------------------+--------+--------+--------+--------+\n  | Array            | O(1)   | O(n)   | O(n)   | O(n)   |\n  | Linked List      | O(n)   | O(n)   | O(1)*  | O(1)*  |\n  | Hash Table       | N/A    | O(1)   | O(1)   | O(1)   |\n  | BST (balanced)   | O(logn)| O(logn)| O(logn)| O(logn)|\n  | Min/Max Heap     | O(1)   | O(n)   | O(logn)| O(logn)|\n  +------------------+--------+--------+--------+--------+\n  * at known position" },
      { id: "ds6", subtopic: "Stacks & Queues", popularity: 8, question: "Implement a Stack using Queues (or Queue using Stacks). What are the trade-offs?", answer: "To implement a stack (LIFO) using two queues, on push: enqueue to the empty queue, then transfer all elements from the other queue. Alternatively, implementing a queue using two stacks involves using one for enqueue and another for dequeue, amortizing the cost.\n\n  STACK using 2 QUEUES (costly push):\n  Push 3: Q1: [3]\n  Push 5: Q2: [5] -> move 3 to Q2 -> Q1: [5,3]\n  Push 7: Q2: [7] -> move all -> Q1: [7,5,3]\n  Pop()  --> returns 7 (front)\n  LIFO order maintained!" },
      { id: "ds7", subtopic: "Linked Lists", popularity: 8, question: "How do you detect a cycle in a Linked List? (Floyd's Algorithm)", answer: "Floyd's Tortoise and Hare algorithm uses two pointers at different speeds: slow advances one node, fast advances two. If a cycle exists, they meet inside the cycle; if fast reaches null, no cycle. O(n) time, O(1) space.\n\n  LIST WITH CYCLE:\n  1 --> 2 --> 3 --> 4 --> 5\n                   ^           |\n                   |           v\n                   8 <-- 7 <-- 6\n\n  +------+------+------+\n  | Step | Slow | Fast |\n  +------+------+------+\n  |  0   |  1   |  1   |\n  |  1   |  2   |  3   |\n  |  2   |  3   |  5   |\n  |  3   |  4   |  7   |\n  |  4   |  5   |  4   |\n  |  5   |  6   |  6   | <-- MEET!\n  +------+------+------+" },
      { id: "ds8", subtopic: "Heaps", popularity: 8, question: "How do you find the Kth largest element in an array using a Min-Heap?", answer: "Maintain a min-heap of size K. As you iterate, if the current element is larger than the heap's root, replace and heapify. After processing all elements, the root is the Kth largest. O(n log k) time.\n\n  ARRAY: [3,2,1,5,6,4]  K=2\n\n  Process 3: Heap: [3]\n  Process 2: Heap: [2,3]      (size=K)\n  Process 1: 1 < root(2)      SKIP\n  Process 5: 5 > root(2)      Replace: [3,5]\n  Process 6: 6 > root(3)      Replace: [5,6]\n  Process 4: 4 < root(5)      SKIP\n\n  Root = 5 = 2nd largest" },
      { id: "ds9", subtopic: "Graphs (Topological Sort)", popularity: 8, question: "Course Schedule: How do you detect if all courses can be completed (topological sort)?", answer: "Given courses and prerequisites, determine if all can be finished (no circular dependency). Use Kahn's algorithm: iteratively remove nodes with zero in-degree. If all removed, valid ordering exists. O(V+E) time.\n\n  COURSES: 0,1,2,3\n  PREREQS: 1->0, 2->0, 3->1, 3->2\n\n  KAHN'S ALGORITHM:\n  +------+-----------+-------+---------+\n  | Step | In-degree | Queue | Order   |\n  +------+-----------+-------+---------+\n  | Init | 0:0 1:1   | [0]   | []      |\n  | Pop 0| 1:0 2:0   | [1,2] | [0]     |\n  | Pop 1| 3:1       | [2]   | [0,1]   |\n  | Pop 2| 3:0       | [3]   | [0,1,2] |\n  | Pop 3|           | []    | [0,1,2,3]|\n  +------+-----------+-------+---------+\n  Valid order: all completable!" },
      { id: "ds10", subtopic: "Tries", popularity: 7, question: "How do you implement an Autocomplete System using a Trie?", answer: "A Trie (prefix tree) is ideal for autocomplete. Each node represents a character, paths form words. Insertion and search run in O(m) time where m is word length. For autocomplete, traverse to the prefix node, then DFS to collect all words below.\n\n  TRIE: 'cat','car','card','care','dog'\n\n        (root)\n        /    \\\n      c        d\n      |        |\n      a        o\n     / \\       |\n    t   r      g*\n    *   |\n       / \\\n      d   e\n      *   *\n\n  Autocomplete 'car':\n  Traverse: root->c->a->r\n  DFS: 'car', 'card', 'care'" },
    ],
  },
  {
    id: "systemdesign",
    label: "System Design",
    icon: "△",
    color: "#a855f7",
    questions: [
      { id: "sd1", subtopic: "URL Shortener", popularity: 10, question: "Design a URL Shortener (e.g., TinyURL, bit.ly)", answer: "Generate a unique short key (Base62 encoding or hash with collision resolution), store the mapping in a key-value database, redirect via HTTP 301/302. Use Redis/Memcached for sub-50ms latency. Read-to-write ratio is ~100:1.\n\n  Client --> Load Balancer --> API Server --> Cache (Redis)\n                                  |             | miss\n                                  v             v\n                             Key Gen Svc    Database (KV)\n\n  WRITE: Client --> API --> Key Gen --> DB --> return short URL\n  READ:  Client --> API --> Cache --hit--> 301 Redirect\n                              +--miss--> DB --> Cache --> 301" },
      { id: "sd2", subtopic: "Chat System", popularity: 9, question: "Design a Chat/Messaging System (e.g., WhatsApp, Messenger)", answer: "Maintain persistent WebSocket connections for real-time delivery. Messages route through a chat service that determines if recipient is online (deliver via WS) or offline (queue + push notification). Group chat uses fan-out. Store history in Cassandra/HBase.\n\n  User A --> Chat Server 1 --> Kafka --> Chat Server 2 --> User B\n                                 |\n                          +-----------+    +-----------+\n                          | Msg Store |    | Presence  |\n                          | (Cassandra)|    | (Redis)   |\n                          +-----------+    +-----------+\n                                                |\n                                          Push Notif Svc\n\n  ONLINE:  A --> Server --> Kafka --> Server --> B (WebSocket)\n  OFFLINE: A --> Server --> Kafka --> Notif --> Push to B" },
      { id: "sd3", subtopic: "Rate Limiter", popularity: 9, question: "Design a Rate Limiter", answer: "Cap API calls per client within a time window, return HTTP 429 when exceeded. Common algorithms: token bucket (allows bursts), leaky bucket (smooth output), fixed/sliding window. Store state in Redis for sub-millisecond lookups. Implement at API gateway level.\n\n  Client --> API Gateway / Rate Limiter\n                  |\n                  v\n             Redis Cluster <--- Rules Engine\n             (counter store)    (limits config)\n                  |\n            +-----+------+\n          ALLOWED      REJECTED\n            |            |\n         App Server   HTTP 429\n\n  TOKEN BUCKET:\n  [Bucket: cap=10, refill=1/sec]\n  Request --> has tokens? --YES--> consume --> forward\n                           --NO--> reject (429)" },
      { id: "sd4", subtopic: "News Feed", popularity: 9, question: "Design a Social Media News Feed (e.g., Facebook, Twitter)", answer: "Two approaches: fan-out-on-write (push — precompute feeds) and fan-out-on-read (pull — assemble at read time). Optimal: hybrid — push for regular users, pull for celebrities. Ranking service applies ML-based relevance scoring.\n\n  WRITE PATH:\n  User posts --> Post Service --> Post DB\n                    |\n              Fan-Out Service\n              /           \\\n  Regular Users        Celebrities\n  (push to cache)     (skip - pull later)\n       |\n  Feed Cache (Redis)\n\n  READ PATH:\n  User request --> Feed Service\n                  (merge cached + pull celebrity posts)\n                       |\n                  Ranking Service\n                  (ML scoring)\n                       |\n                  Ranked Feed --> Client" },
      { id: "sd5", subtopic: "Notification System", popularity: 8, question: "Design a Notification System", answer: "Decouple triggering from delivery. Accept requests via Notification Service, check user preferences, enqueue into prioritized Kafka topics. Workers consume and route to appropriate channel (push, email, SMS). Handle failures with DLQ and retries.\n\n  Triggering Services\n       |\n  Notification Service\n  (validate, enrich, prioritize)\n       |\n  +---User Prefs---+---Templates---+\n       |\n  Message Queue (Kafka)\n  [High] [Med] [Low]\n       |       |       |\n  Push Worker  Email   SMS Worker\n  (APNs/FCM)  (SES)   (Twilio)\n       |\n  Dead Letter Queue (failed + retries)" },
      { id: "sd6", subtopic: "Database Sharding", popularity: 7, question: "Design Database Sharding", answer: "Split a large database into smaller shards across multiple servers. Shard key selection is critical — a good key distributes evenly and keeps related queries on one shard. Common strategies: hash-based, range-based, directory-based. Consistent hashing with virtual nodes minimizes data movement during rebalancing.\n\n  App Layer --> Query Router / Shard Proxy\n                    |\n           +--------+--------+\n           |        |        |\n        Shard 1  Shard 2  Shard 3\n        (A-G)   (H-P)    (Q-Z)\n           |        |        |\n        Replica  Replica  Replica\n\n  Hash-Based:  shard = hash(id) % N\n  Range-Based: shard1=[A-G], shard2=[H-P]\n  Consistent Hash: ring with virtual nodes\n  (adding shard moves only ~1/N of data)" },
      { id: "sd7", subtopic: "File Storage", popularity: 7, question: "Design a File Storage System (e.g., Google Drive, Dropbox)", answer: "Files are split into chunks (~4MB), each identified by content hash (SHA-256) for deduplication and delta sync. Metadata (hierarchy, permissions, versions) in relational DB. Chunks stored in object storage (S3). Sync service uses long polling/WebSockets.\n\n  Client App\n       |\n  +----------+---------+-----------+\n  | Upload   | Download| Sync Svc  |\n  | Service  | Service | (WebSocket)|\n  +----+-----+----+----+-----+-----+\n       |          |          |\n  Chunking &  Chunk       Notif Queue\n  Dedup       Assembly    (device sync)\n       |          |\n  Object Storage (S3) - stores chunks by hash\n  Metadata DB (Postgres) - file tree, versions" },
      { id: "sd8", subtopic: "Search Autocomplete", popularity: 7, question: "Design a Search Autocomplete / Typeahead System", answer: "Core data structure: Trie with pre-computed top-K suggestions at each node. At scale, partition via range-based sharding. Reads/writes decoupled: queries hit in-memory trie, updates happen via batch processing of search logs. Cache aggressively at CDN.\n\n  User types --> Client (debounce 50ms)\n       |\n  CDN/Edge Cache (popular prefixes)\n       | miss\n  API Gateway --> Autocomplete Service\n                    |\n              +-----+------+\n           Shard A-M   Shard N-Z\n           (Trie in    (Trie in\n            memory)     memory)\n\n  ASYNC UPDATE:\n  Search Logs --> Batch Processor --> Trie Builder\n                                     --> atomic swap to servers" },
      { id: "sd9", subtopic: "CDN", popularity: 6, question: "Design a CDN (Content Delivery Network)", answer: "Geographically distributed edge servers that cache content close to users. DNS resolves to nearest edge (anycast/geo-DNS). Cache hit: serve directly (<10ms). Cache miss: fetch from shield/origin, cache locally with TTL. Invalidation via TTL, purge APIs, or versioned URLs.\n\n  User(Tokyo)    User(NYC)     User(London)\n       |              |              |\n  Edge PoP Tokyo Edge PoP NY   Edge PoP London\n       |              |              |\n       +------- Shield Cache --------+\n                     |\n                Origin Server (S3/App)\n\n  Flow: User --> DNS(geo) --> Edge\n  Edge HIT --> serve (fast)\n  Edge MISS --> Shield/Origin --> cache --> serve" },
      { id: "sd10", subtopic: "Load Balancer", popularity: 6, question: "Design a Load Balancer", answer: "Distributes traffic across backend servers. Operates at Layer 4 (TCP — fast, based on IP/port) or Layer 7 (HTTP — smart, routes by URL/headers/cookies). Algorithms: round-robin, weighted round-robin, least connections, consistent hashing. Health checks detect unhealthy servers.\n\n  Internet --> DNS LB (geographic)\n                 |\n            L4 LB (TCP, NLB)\n                 |\n           +-----+-----+\n           |     |     |\n         L7 LB L7 LB L7 LB (Nginx/HAProxy)\n           |     |     |\n         Svrs  Svrs  Svrs\n\n  Health Check: LB --ping--> Server\n  Healthy? keep in pool / Unhealthy? remove\n\n  Algorithms:\n  Round Robin:      A->B->C->A->B->C\n  Least Connections: route to least busy\n  Consistent Hash:  hash(ip) --> sticky server" },
    ],
  },
  {
    id: "mycareer",
    label: "My Career",
    icon: "★",
    color: "#E8A838",
    questions: [
      { id: "cv1", subtopic: "RAG & AI Systems", popularity: 10, question: "You mention building RAG systems with pgVector and Qdrant. Walk me through the full pipeline — from document ingestion to semantic retrieval. What chunking strategy did you use and why?", answer: "At Lex Consultoria, I built a RAG system integrated with TOTVS ERP for HR queries. The pipeline starts with document ingestion (PDFs, structured data from the ERP), then I chunk documents using a sliding window approach with overlap (typically 512 tokens with 50-token overlap) to preserve context across boundaries. Each chunk is embedded using OpenAI's text-embedding-ada-002 and stored in pgVector. At query time, the user's question is embedded and a cosine similarity search retrieves the top-k relevant chunks, which are injected into the prompt context for GPT-4 to generate a grounded answer. I chose pgVector over standalone vector DBs because the HR data already lived in PostgreSQL, avoiding an extra infrastructure dependency. At TateAI I used Qdrant for the backlog management platform because we needed faster similarity search at scale with filtering capabilities." },
      { id: "cv2", subtopic: "System Architecture", popularity: 10, question: "At BTG Pactual you processed $10M+ daily transactions. How did you architect the system for reliability at that scale? What happens when a downstream service fails?", answer: "The financial system at BTG was built on a serverless microservices architecture using AWS Lambda, DynamoDB, and Kafka for event streaming. Each transaction goes through an API Gateway, hits a Lambda function for validation and business logic, then publishes to a Kafka topic. Downstream consumers process events independently. For reliability: we used DynamoDB with strongly consistent reads for critical financial data, implemented idempotency keys to prevent duplicate transactions on retries, and used dead letter queues (SQS DLQ) for failed events. Circuit breakers prevented cascading failures. We achieved 99.9% uptime with 200ms average latency." },
      { id: "cv3", subtopic: "Real-time Systems", popularity: 9, question: "You handled 1000+ concurrent WebSocket connections for chat streaming at TateAI. How did you manage connection lifecycle, backpressure, and scaling?", answer: "At TateAI, the chat system used WebSocket connections for real-time LLM streaming. Each connection is managed with a connection registry that tracks user sessions, handles heartbeats, and performs graceful cleanup on disconnect. For backpressure with LLM streaming, I implemented token-level streaming where the server receives tokens from the LLM API and immediately forwards them to the client — if the client's buffer is full, we pause the upstream read. Scaling was handled by running multiple Node.js instances behind a load balancer with sticky sessions, and we used Redis pub/sub to broadcast messages across instances." },
      { id: "cv4", subtopic: "Migration & Optimization", popularity: 9, question: "You led migrating Java services to Node.js at BTG Pactual, reducing costs by 35%. How did you approach this migration without downtime?", answer: "The migration followed a strangler fig pattern — we didn't rewrite everything at once. I identified the highest-cost, lowest-complexity Java services as migration candidates. I built the Node.js replacement alongside the Java service, then used API Gateway weighted routing to gradually shift traffic (10%, 25%, 50%, 100%) while monitoring error rates and latency. Cost savings came from Lambda's pay-per-invocation model vs. always-on Java ECS containers, plus Node.js's lower memory footprint. Response times improved 45% because Node.js handles I/O-bound workloads more efficiently." },
      { id: "cv5", subtopic: "Telemedicine Platform", popularity: 9, question: "Tell me about the telemedicine platform at Lex Consultoria. How did you handle video call reliability, medical data security, and serving 20,000+ employees?", answer: "The telemedicine platform integrates Jitsi for video calls (self-hosted for data sovereignty), a real-time chat system, and secure medical document upload. For video reliability, we implemented automatic quality adaptation based on network conditions, fallback to audio-only, and reconnection logic with session persistence. Medical data security follows LGPD: documents are encrypted at rest (AES-256) and in transit (TLS 1.3), stored in S3 with bucket policies restricting access, and all access is logged for audit. The React frontend uses WebSocket for real-time presence indicators and push notifications. We serve 20,000+ employees with role-based access." },
      { id: "cv6", subtopic: "AI-Assisted Development", popularity: 8, question: "You claim shipping features 3x faster using AI-assisted development tools. Can you give a concrete example? How do you ensure code quality?", answer: "At BTG Pactual, a CRM feature that previously took 1-2 weeks I could deliver in 2-3 days using Claude Code for architecture scaffolding, Copilot for boilerplate, and Amazon Q for AWS configurations. A concrete example: building a new financial report module — I used Claude Code to generate the Prisma schema, API routes with validation, and React components with proper TypeScript types, then reviewed and refined each piece. Quality assurance is critical: I never blindly accept AI output. I review every line for security issues, verify business logic, run the full test suite, and do manual testing." },
      { id: "cv7", subtopic: "E-commerce & Performance", popularity: 8, question: "At FAVO you achieved 60% latency reduction. What specific optimizations did you make?", answer: "Bottleneck analysis started with distributed tracing and CloudWatch metrics. Main issues: 1) N+1 query problems in order creation — I introduced DataLoader-style batching and denormalized frequently-read data into DynamoDB. 2) Cold starts on Lambda — implemented provisioned concurrency for critical paths and reduced package sizes. 3) Synchronous API calls to external services — moved to event-driven with SQS queues for non-critical operations. 4) Frontend: code splitting, image optimization, and Redis caching for product catalog with 5-minute TTL. Combined: 60% reduction in P95 latency (from ~2.5s to ~1s), and conversion rate improved 35%." },
      { id: "cv8", subtopic: "Leadership", popularity: 8, question: "As a Tech Lead at Lex, how do you balance hands-on coding with leadership responsibilities?", answer: "I allocate roughly 60% coding and 40% leadership (code reviews, mentoring, planning, stakeholder communication). For architectural decisions, I write lightweight ADRs for significant choices — like choosing pgVector over a standalone vector DB. I present options with trade-offs to the team, encourage discussion, but ultimately take responsibility for the decision. For mentoring, I do pair programming sessions with junior developers on complex features, and I set up coding standards and review processes. The best tech leads stay close to the code — it keeps you honest about estimates and means you can jump in during critical situations." },
      { id: "cv9", subtopic: "Anomaly Detection", popularity: 7, question: "How does your anomaly detection system with Gemini work for time-tracking at Lex?", answer: "The system analyzes employee time-tracking data from TOTVS ERP using Gemini's API. Anomalies include: excessive overtime patterns, clock-in/out at unusual hours, missing entries on working days, and inconsistencies between logged hours and expected workload. I feed structured data to Gemini with a carefully engineered prompt defining anomaly categories and asking for confidence scores. To avoid false positives: I set a confidence threshold (only flag items above 80%), cross-reference with known exceptions (holidays, approved overtime, shift workers), and managers review flagged items before action. Saves 20+ hours/week of manual review." },
      { id: "cv10", subtopic: "Serverless Architecture", popularity: 8, question: "You've used AWS Lambda extensively. What are the real-world limitations you've hit, and how did you work around them?", answer: "Main limitations: 1) Cold starts — for financial APIs where latency matters, I used provisioned concurrency and kept warm pools with scheduled pings. 2) 15-minute execution timeout — for long-running tasks like document processing in the RAG pipeline, I used Step Functions to orchestrate multi-step workflows. 3) Package size limits (250MB) — I used Lambda Layers for shared dependencies and aggressive tree-shaking. 4) Statelessness — I used RDS Proxy for PostgreSQL connection management. 5) Vendor lock-in — I kept business logic in framework-agnostic modules with thin Lambda handlers. At FAVO, this handled 100,000+ daily requests at 99.95% availability." },
    ],
  },
];

export const uid = () => Math.random().toString(36).slice(2, 9);

export function buildPrompt(topic, subtopic, count) {
  return `You are a senior software engineer preparing interview questions for developers specialising in TypeScript, React, and Node.js.

Generate exactly ${count} high-quality technical interview questions with detailed answers for the following:
- Topic: ${topic}
- Subtopic: ${subtopic}

Requirements:
- Questions should range from mid to senior level.
- Answers must be detailed (3–5 sentences minimum), accurate, and mention real-world usage.
- Include code snippets or examples where relevant (use plain text, no markdown fences).
- Cover different angles: conceptual understanding, practical usage, trade-offs.

Respond ONLY with a valid JSON array. No preamble, no markdown, no backticks.
Format:
[
  {
    "question": "...",
    "answer": "..."
  }
]`;
}
